### ISSUE TITLE
jbang edit does not symlink wildcards included files

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#1005]
Having the following source Main.java using multiple source files:

`
///usr/bin/env jbang "$0" "$@" ; exit $?

//SOURCES **/*.java

public class Main {
    public static void main(String... args) {
        new Left();
        new Right();
    }
}
`

which includes two other files Left.java and Right.java.

If i edit Main.java with:

`jbang edit --open Main.java`

Main.java does not compile in the IDE because Left.java and Right.java have not been symlinked in the temporary edit folder.

**Comment by grumpyf0x48** [comment]
It is normal !

Should be:

`//SOURCES *.java`

**Comment by grumpyf0x48** [comment]
Have found a working configuration:

```
//SOURCES *.java
//FILES templates/junit4.java.qute
//FILES templates/junit5.java.qute
//FILES README.md

public class Catalog {
}
```

But strangely cant make it work using wilcards to include all files in the templates folder :-)

For example:

```
//SOURCES *.java
//FILES **/*.qute
//FILES README.md

public class Catalog {
}
```

```
jbang edit --verbose --open Catalog.java 
[jbang] jbang version 0.79.0
[jbang] [ERROR] Could not find **/*.qute
dev.jbang.cli.ExitException: Could not find **/*.qute
	at dev.jbang.source.ResourceRef.asSibling(ResourceRef.java:80)
	at dev.jbang.source.RefTarget.create(RefTarget.java:83)
	at dev.jbang.source.RefTarget.create(RefTarget.java:79)
	at dev.jbang.source.ScriptSource.toFileRef(ScriptSource.java:479)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at dev.jbang.source.ScriptSource.collectFiles(ScriptSource.java:475)
	at dev.jbang.source.ScriptSource.collectAll(ScriptSource.java:532)
	at dev.jbang.source.ScriptSource.getAllFiles(ScriptSource.java:462)
	at dev.jbang.cli.Edit.createProjectForEdit(Edit.java:251)
	at dev.jbang.cli.Edit.doCall(Edit.java:73)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

I've tried `*.java.qute` and i get the same error.
