### ISSUE TITLE
Unknown catalog 'quarkus'

### ISSUE THREAD

**Issue by liononon** [jbangdev/jbang#1022]
Caused by: java.io.FileNotFoundException: No file to download at https://bitbucket.org/quarkus/jbang-catalog/raw/HEAD/jbang-catalog.json. Server replied HTTP code: 404
	at dev.jbang.util.Util.downloadFile(Util.java:609)
	at dev.jbang.util.Util.downloadFile(Util.java:529)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:704)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:676)
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:326)
	... 34 more
[jbang] [ERROR] Unknown catalog 'quarkus'

**Comment by maxandersen** [comment]
What command are you running ?

**Comment by maxandersen** [comment]
going to assume this is related to https://github.com/quarkusio/quarkus/issues/20403#issuecomment-927525267

In this case it looks like you have call `jbang catalog list quarkus` where it should have been `jbang catalog list quarkusio` as there is actually no catalog called quarkus. so its working as expected.

closing.
