### ISSUE TITLE
--cp causing NPE with integration manager

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1143]
**Describe the bug**
jbang --cp lib/jbang.jar genadoc.jar causes NPE as no artifact version number of lib/jbang.jar.

```
jbang --cp build/libs/jbang.jar --verbose docs/genadoc.java -d docs/modules/cli --force --verbose dev.jbang.cli.JBang
[jbang] jbang version 0.84.2.23
[jbang] System Java version detected as 11
[jbang] System Java version 11 incompatible, using JBang managed version 16
[jbang] Building jar...
[jbang] compile: /Users/max/.jbang/cache/jdks/16/bin/javac -classpath /Users/max/.m2/repository/info/picocli/picocli/4.6.1/picocli-4.6.1.jar:/Users/max/.m2/repository/info/picocli/picocli-codegen/4.6.1/picocli-codegen-4.6.1.jar:/Users/max/code/personal/jbangdev/jbang/build/libs/jbang.jar -d /Users/max/.jbang/cache/jars/genadoc.java.06f9b7f57847fe65aad6728b12f78563460e275bf2cdfb0596df6349c478fa2c.jar.tmp /Users/max/code/personal/jbangdev/jbang/docs/genadoc.java
[jbang] Deleting folder /Users/max/.jbang/cache/jars/genadoc.java.06f9b7f57847fe65aad6728b12f78563460e275bf2cdfb0596df6349c478fa2c.jar.tmp
[jbang] [ERROR] public class java.lang.NullPointerException
java.lang.NullPointerException
	at dev.jbang.spi.IntegrationManager.lambda$runIntegration$4(IntegrationManager.java:78)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at dev.jbang.spi.IntegrationManager.runIntegration(IntegrationManager.java:80)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:200)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:131)
	at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:95)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:100)
	at dev.jbang.cli.Run.doCall(Run.java:76)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
	at dev.jbang.cli.JBang$3.handle(JBang.java:140)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**Comment by maxandersen** [comment]
main has fix to avoid the NPE but issue is that current integration manager does not work with --cp as GAV not known for each entry.

**Comment by maxandersen** [comment]
this was fixed recently
