### ISSUE TITLE
`jbang wrapper install` throws NPE  @v0.88.0

### ISSUE THREAD

**Issue by someth2say** [jbangdev/jbang#1233]
**Describe the bug**
`jbang wrapper install` crashes with a NPE:
```
✗ jbang wrapper install --force --verbose
[jbang] jbang version 0.88.0
[jbang] [ERROR] Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null
        at java.base/java.nio.file.Files.provider(Files.java:105)
        at java.base/java.nio.file.Files.isDirectory(Files.java:2316)
        at dev.jbang.cli.Wrapper.install(Wrapper.java:28)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.JBang$3.handle(JBang.java:145)
        at dev.jbang.cli.JBang$3.handle(JBang.java:140)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**To Reproduce**
1. Install the v0.88.0
2. run `jbang wrapper install`

**Expected behavior**
The wrapper is created without errors.

**JBang version**
[jbang] jbang version 0.88.0
Cache: /Users/jordisola/.jbang/cache
Config: /Users/jordisola/.jbang
Repository:/Users/jordisola/.m2/repository
0.88.0

**Additional context**
The same fails for both Mac and Linux versions.

**Comment by maxandersen** [comment]
hmm - bummer  - I can confirm that does happen! investigating!

**Comment by maxandersen** [comment]
fyi - workaround is `jbang wrapper install -d .`

**Comment by maxandersen** [comment]
@quintesse looks like what is different here is that wrapper is implemented using command methods rather than as command classes - and thus somehow `wrapper.dir` is not being applied properly here.

Anything that rings a bell?
