### ISSUE TITLE
NPE when running -c with -s args

### ISSUE THREAD

**Issue by davsclaus** [jbangdev/jbang#1246]
```
~/workspace/deleteme ❯ cat hello.jsh
println("hello")%
~/workspace/deleteme ❯ jbang -c -s=hello.jsh --verbose
[jbang] jbang version 0.90.0
[jbang] [ERROR] public class java.lang.NullPointerException
java.lang.NullPointerException
	at dev.jbang.util.Util.getStableID(Util.java:916)
	at dev.jbang.source.resolvers.LiteralScriptResourceResolver.stringToResourceRef(LiteralScriptResourceResolver.java:51)
	at dev.jbang.cli.Run.doCall(Run.java:97)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
	at dev.jbang.cli.JBang$3.handle(JBang.java:140)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
~/workspace/deleteme ❯ jbang -c 'println("hello")'
hello

~/workspace/deleteme ❯ jbang hello.jsh
hello
```

**Comment by davsclaus** [comment]
Awesome with the new `-c` mode. However I could not get it to run when I have the code as a script file, and use the `-s` parameter.

It could maybe be that `-s` is to load additional source as script and that there are no actual script from the command line. 
So it may be an end user mistaken, but jbang reported a NPE which I thought you guys may want to see.

**Comment by quintesse** [comment]
@davsclaus thanks for the bug report. It happens when you use `-c` without giving it any code. jbang should report a missing required parameter error in that case.

**Comment by davsclaus** [comment]
Thanks for the explanation and great that you already have a fix as a PR.
