### ISSUE TITLE
java.lang.ClassNotFoundException: /util/logging/manager when executing gist

### ISSUE THREAD

**Issue by ice09** [jbangdev/jbang#1253]
**Describe the bug**
On `jbang https://gist.github.com/ice09/27ab92c93469a4bc0dbb0b84a2299033` I get the exception below. I tried adding `//DEPS org.jboss.logmanager:log4j-jboss-logmanager:1.2.1.Final` manually, but to no avail.

Locally, both versions (with manual logmanager and without) do work.

**First try**
```
[jbang] Resolving dependencies...
[jbang] Artifacts used for dependency management:
         io.quarkus:quarkus-bom:pom:1.11.0.Final
[jbang] io.quarkus:quarkus-resteasy
         io.quarkus:quarkus-resteasy-jackson
         io.quarkus:quarkus-smallrye-openapi
         io.quarkus:quarkus-swagger-ui
         org.jboss.logmanager:log4j-jboss-logmanager:jar:1.2.1.Final
Done
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] Post build with io.quarkus.launcher.JBangIntegration
Feb. 24, 2022 9:50:26 VORM. org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.2.0.Final
Feb. 24, 2022 9:50:27 VORM. io.quarkus.deployment.QuarkusAugmentor run
INFO: Quarkus augmentation completed in 881ms
Fehler: Hauptklasse .util.logging.manager=org.jboss.logmanager.LogManager konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: /util/logging/manager=org/jboss/logmanager/LogManager
```

**Subsequent**
```
Fehler: Hauptklasse .util.logging.manager=org.jboss.logmanager.LogManager konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: /util/logging/manager=org/jboss/logmanager/LogManager
```

**To Reproduce**
`jbang https://gist.github.com/ice09/27ab92c93469a4bc0dbb0b84a2299033`

**Expected behavior**
Should start a REST service, which also works in local version (`jbang ZipCityConverter.java`)

**JBang version**
```
[jbang] jbang version 0.90.1
Cache: C:\Users\alexa\.jbang\cache
Config: C:\Users\alexa\.jbang
Repository:C:\Users\alexa\.m2\repository
0.90.1
```

**Comment by maxandersen** [comment]
I cannot reproduce.

Can you try running with `jbang --fresh https://gist.github.com/ice09/27ab92c93469a4bc0dbb0b84a2299033` to ensure it is running with a fresh build ?

**Comment by maxandersen** [comment]
btw. https://gist.github.com/ice09/27ab92c93469a4bc0dbb0b84a2299033#file-zipcityconverter-java-L43 tries to load the json resource using a file - to make it work you'll need to load it as a resource via classloading.

**Comment by ice09** [comment]
* I tried with --fresh, but same result. 
* I removed the manually added DEPS again and used ClassPathResource

Error still prevails. I am using OpenJDK 11:

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by maxandersen** [comment]
Weird. Makes no sense that it works locally but not via git as the git url just gets downloaded locally and run so effectively should be the same. 

Try "jbang cache clear" and see if works after that.

**Comment by ice09** [comment]
Nice, that fixes it. It get a WARN stacktrace, but it works now.

The stacktrace is
```
Feb 24, 2022 9:33:45 PM io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext getEffectiveSettings
WARN: Settings problem encountered at /home/hal9000/.sdkman/candidates/maven/current/conf/settings.xml, line 164, column 16
org.apache.maven.settings.io.SettingsParseException: Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\r\n      <blocked>... @164:16)
        at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:87)
        at org.apache.maven.settings.building.DefaultSettingsBuilder.readSettings(DefaultSettingsBuilder.java:182)
        at org.apache.maven.settings.building.DefaultSettingsBuilder.build(DefaultSettingsBuilder.java:104)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getEffectiveSettings(BootstrapMavenContext.java:252)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getActiveSettingsProfiles(BootstrapMavenContext.java:530)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.resolveRemoteRepos(BootstrapMavenContext.java:470)
        at io.quarkus.bootstrap.resolver.maven.BootstrapMavenContext.getRemoteRepositories(BootstrapMavenContext.java:231)
        at io.quarkus.bootstrap.jbang.JBangBuilderImpl.postBuild(JBangBuilderImpl.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.launcher.JBangIntegration.postBuild(JBangIntegration.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at dev.jbang.spi.IntegrationManager.runIntegration(IntegrationManager.java:117)
        at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:221)
        at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:152)
        at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:98)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:134)
        at dev.jbang.cli.Run.doCall(Run.java:109)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.JBang$3.handle(JBang.java:145)
        at dev.jbang.cli.JBang$3.handle(JBang.java:140)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'blocked' (position: START_TAG seen ...</url>\r\n      <blocked>... @164:16)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.checkUnknownElement(SettingsXpp3Reader.java:149)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseMirror(SettingsXpp3Reader.java:920)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseSettings(SettingsXpp3Reader.java:1416)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:1544)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:566)
        at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:595)
        at org.apache.maven.settings.io.DefaultSettingsReader.read(DefaultSettingsReader.java:83)
        ... 33 more
```

Thanks, I will close this.

**Comment by ice09** [comment]
Sorry, just realized that I started it in WSL2, which works (with the warning) - with Powershell I still face the original issue. For me, that it fine, however you probably want to investigate further, just let me know.

**Comment by ice09** [comment]
And in normal Windows Command line it works, so:
* in WSL2: had to change the `settings.xml` (remove `blocked`) and it worked
* in Powershell: does not work (see above)
* in Windows Shell (cmd): does work out of the box

Hope this helps.

**Comment by quintesse** [comment]
This is caused by the command overflowing the PowerShell's input buffer. When I run the same command that gets used by the CMD shell then things work just fine.

**Comment by quintesse** [comment]
It's weird because according to info on the Web the PS max length should be 32K. But obviously that isn't right. So I guess we'll just have to apply the same logic for PowerShell as for CMD. (That is we change [this line](https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/cli/Run.java#L167) to say `!= Util.Shell.bash` )

**Comment by maxandersen** [comment]
so with gist and powershell it fails but local and powershell it works locally or fails all the time in powershell?

**Comment by quintesse** [comment]
I have only tried the Gist, but I expect it to always fail because the command line it generates is just enormous (> 10K).

**Comment by ice09** [comment]
Ah, that nailed it! Sorry, I started the local version from IntelliJ which uses CMD I assume. So that's the error, it does _not depend_ on gist or local usage, it is the same behaviour in both cases:

* in WSL2: had to change the `settings.xml` (remove blocked) and it worked
* in Powershell: does not work (see above)
* in Windows Shell (cmd): does work out of the box

For the `settings.xml` change I think it is related to the sdkman installation in WSL2. So the only error is the Powershell Buffer problem @quintesse mentioned.

**Comment by maxandersen** [comment]
Ack. Then it all makes sense. Thank you!

@quintesse will you open pr for that change ?

**Comment by quintesse** [comment]
@maxandersen I've made it part of that refactor I'm working on because it directly affects the same code. I hope that's okay with you.

**Comment by maxandersen** [comment]
Alright :)
