### ISSUE TITLE
Specifying --trust=* is too hard on windows

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang#129]
I have been trying in several ways to specify --trust=* on Windows without success. Often strange values get inserted and once that even resulted in an illegal JSON file that broke jbang completely (it would throw parse exceptions straight away).

In the end I had to insert a dummy trust value and then edit the resulting file and change it to *.

**Comment by maxandersen** [comment]
strange values ??

**Comment by maxandersen** [comment]
* is a glob character in most shells - if you don't quote it you get funky results.

`jbang --trust="*"` should just work.

**Comment by maxandersen** [comment]
i.e. the "strange" values I get is result of auto expanded files. all still valid json.

I haven't found a way to make it cause illegal json - if you can reproduce that i would be interested.

**Comment by quintesse** [comment]
> is a glob character in most shells - if you don't quote it you get funky results.

This is on Window, globbing isn't handled by the shell but by the apps themselves. (Eg. if you type `echo *` you'll just get `"`).

But I'll add some steps to reproduce. Just haven't had time yet and wanted to make sure I didn't forget about this.

**Comment by quintesse** [comment]
Ok, so using [test.java](https://github.com/jbangdev/jbang/files/4786024/test.java.txt) this is what I found executing the following command in CMD:

```
> jbang test.java trust=*
[trust, test.java]

> echo jbang test.java trust=*
jbang test.java trust=*

> jbang test.java "trust=*"
[trust=*]
```

And in PowerShell:

```
> jbang test.java trust=*
[trust, test.java]

> echo jbang test.java trust=*
jbang
test.java
trust=*

> jbang test.java "trust=*"
[trust, test.java]

> jbang test.java '"trust=*"'
[trust=*]
```

Something is obviously doing glob expansion, it must be picocli itself doing that. And more importantly is that when using PowerShell you need double quoting (single around double, something I found on StackOverflow is needed when you need to pass arguments that contain =-signs).

So, this issue can probably be solved by perhaps adding a bit of Windows-specific documentation to the README.

Will look into the illegal JSON later on.

**Comment by quintesse** [comment]
Ok, was able to reproduce:

```
> jbang --trust=\*
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 17 column 8 path $[2]
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at dk.xam.jbang.TrustedSources.load(TrustedSources.java:31)
        at dk.xam.jbang.Settings.getTrustedSources(Settings.java:113)
        at dk.xam.jbang.Main.doCall(Main.java:245)
        at dk.xam.jbang.Main.call(Main.java:373)
        at dk.xam.jbang.Main.call(Main.java:73)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at dk.xam.jbang.Main.main(Main.java:204)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 17 column 8 path $[2]
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
        at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1555)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1015)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:816)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 16 more
```

And after that trying to execute anything from a URL gives:

```
> jbang https://github.com/jbangdev/jbang/blob/master/examples/findmodule.java
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 17 column 8 path $[2]
        at com.google.gson.Gson.fromJson(Gson.java:947)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at dk.xam.jbang.TrustedSources.load(TrustedSources.java:31)
        at dk.xam.jbang.Settings.getTrustedSources(Settings.java:113)
        at dk.xam.jbang.Main.fetchFromURL(Main.java:1110)
        at dk.xam.jbang.Main.getScriptFile(Main.java:1000)
        at dk.xam.jbang.Main.prepareScript(Main.java:906)
        at dk.xam.jbang.Main.doCall(Main.java:316)
        at dk.xam.jbang.Main.call(Main.java:373)
        at dk.xam.jbang.Main.call(Main.java:73)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at dk.xam.jbang.Main.main(Main.java:204)
Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 17 column 8 path $[2]
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
        at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1555)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1015)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:816)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        ... 19 more
```

Until you manually clean up the `trusted-sources.json` file.

And the reason seems to be that `\*` gets expanded to the list of files and folders in the root of the drive which in Windows includes a hidden folder called `$Recycle.Bin` so what gets inserted into the JSON file is `"\$Recycle.Bin"`. I don't know why the value doesn't get properly escaped but `\$` is obviously not correct.

**Comment by quintesse** [comment]
Ha, actually in Linux it fails as well!

```
$ jbang '--trust=\*'
```

simply inserts `"\*"` into the JSON, wow.

**Comment by quintesse** [comment]
Ah, that's probably because you're using a somewhat strange way to write that file. Why are you using Qute templates and not just Gson?

**Comment by quintesse** [comment]
Btw, a way to provide comments that doesn't result in an illegal JSON file could be this:

```json
{
  "_comment_": [
    "URL's matching one or more entries in the list below will be trusted to be runnable by jbang.",
    "The following examples show what entries can look like:",
    "- 'https://jbang.dev': Matches this specific domain using https",
    "- 'https://jbang.dev/foo': Matches https://jbang.dev/foo and https://jbang.dev/foo/bar,",
    "  but not https://jbang.dev/foobar or https://jbang.dev/bar",
    "- 'https://*.jbang.dev': Match all domains ending in 'jbang.dev' using https",
    "- 'jbang.dev': Match this specific domain using either http or https",
    "- '*.jbang.dev': Match all domains ending in 'jbang.dev' using either http or https",
    "- '*': Match all sources using either http or https (This effectively disables any checks. Be careful!)",
    "",
    "By default, jbang trusts 'localhost' and file://.",
    "You can use the 'jbang --trust=rule1,rule2,..' command to add to this file.",
    "Note: --trust will rewrite this file. Preserving just the elements. Additional data and comments will not be kept."
  ],
  "trusted": []
}
```

It's not particularly nice but it would avoid problems with that file not being actually legal JSON and being able to use the proper tools for reading and writing...

Another option is to switch to YAML  instead of JSON.

**Comment by maxandersen** [comment]
its a jsonc file - supports comments ;) 

But i don't get where * should be doing expansion in picocli - it doesn't afaics.

I wonder if its in jbang.bat the expansion happens ?

**Comment by quintesse** [comment]
> its a jsonc file - supports comments ;)

Totally non-standard, as you can see by the broken file that gets generated ;-)

**Comment by quintesse** [comment]
> I wonder if its in jbang.bat the expansion happens ?

Yup, just tested it and it's the .bat script that causes the problem

**Comment by quintesse** [comment]
Fix is simple. The `FOR` needs that double quoting I mentioned before. I'll provide a patch.

**Comment by maxandersen** [comment]
> Totally non-standard, as you can see by the broken file that gets generated ;-)

its not the comments that are causing issues but that the qute generation aren't doing proper json quoting.

**Comment by maxandersen** [comment]
found that the json dumping was not escaping strings right - fixed in master now
