### ISSUE TITLE
Windows WSL Ubuntu error

### ISSUE THREAD

**Issue by axkr** [jbangdev/jbang#1354]
I try to run `jbang symjajsh@axkr` as described here
* https://github.com/axkr/jbang-catalog/pull/1

with WIndows WSL Ubuntu and get an error:
```
Caused by: java.net.MalformedURLException: unknown protocol: org.matheclipse
```

Do I have to install Maven separatly first?

```
dev@DESKTOP-6LF86RL:~$ jbang --verbose symjajsh@axkr
[jbang] jbang version 0.93.0
[jbang] Reading catalog from /home/dev/.jbang/implicit-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/axkr/jbang-catalog/HEAD/jbang-catalog.json = /home/dev/.jbang/cache/urls/cba52fbe16567e383c98a35ac557a18209bfad578dbf255a70ce2bf41ac02f40/jbang-catalog.json
[jbang] Reading catalog from /home/dev/.jbang/cache/urls/cba52fbe16567e383c98a35ac557a18209bfad578dbf255a70ce2bf41ac02f40/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/axkr/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Duplicating classpath resource jbang-catalog.json
[jbang] Reading catalog from /home/dev/.jbang/cache/urls/2c97f3a787487bf73b7f4d02e109487e0e43be594ef95072827efd1500cd99ae
[jbang] Retrieved file from cache https://raw.githubusercontent.com/axkr/symja_android_library/master/symja_android_library/start-symja.jsh = /home/dev/.jbang/cache/urls/464f1a7af0d976aa0f24236c65853a68126a2e732cd2d2a477f372a34f99a836/start-symja.jsh
[jbang] Resolving dependencies...
[jbang] [ERROR] invalid URL
java.lang.IllegalArgumentException: invalid URL
        at org.jboss.shrinkwrap.resolver.api.maven.repository.MavenRemoteRepositories.createRemoteRepository(MavenRemoteRepositories.java:45)
        at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:59)
        at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:36)
        at dev.jbang.dependencies.MavenRepo.apply(MavenRepo.java:32)
        at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$1(DependencyUtil.java:152)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:152)
        at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:122)
        at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:71)
        at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:67)
        at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:354)
        at dev.jbang.source.generators.JshCmdGenerator.generateCommandLineList(JshCmdGenerator.java:35)
dev@DESKTOP-6LF86RL:~$
        at dev.jbang.cli.Run.doCall(Run.java:103)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.JBang$3.handle(JBang.java:145)
        at dev.jbang.cli.JBang$3.handle(JBang.java:140)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: java.net.MalformedURLException: unknown protocol: org.matheclipse
        at java.base/java.net.URL.<init>(URL.java:652)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at org.jboss.shrinkwrap.resolver.api.maven.repository.MavenRemoteRepositories.createRemoteRepository(MavenRemoteRepositories.java:42)
        ... 24 more
```

I installed jbang this way:
```
dev@DESKTOP-6LF86RL:~$ curl -Ls https://sh.jbang.dev | bash -s - app setup
Downloading JBang...
Installing JBang...
Downloading JDK 11. Be patient, this can take several minutes...
Installing JDK 11...
[jbang] Default JDK set to 11
[jbang] Setting up JBang environment...
Please start a new Shell for changes to take effect
```

**Comment by maxandersen** [comment]
no maven required - whole point is that you dont need extras.

I'm a bit perplexed by the error as I just see it resolving dependencies and all is good - even in wsl2.

can you paste the content of 👍 
`https://raw.githubusercontent.com/axkr/symja_android_library/master/symja_android_library/start-symja.jsh`

and then do a `jbang cache clear` and try again?

btw. the point of the symjajsh is it gets used interactively with jsh so you would do `jbang symjajsh@axkr -i` to get the interactive part.

**Comment by maxandersen** [comment]
btw. what is weird about the error is that it somehow thing org.mathclipse is a repository specified with //REPOS or --repos but I dont see any of that in this

**Comment by axkr** [comment]
> can you paste the content of 👍
> `/home/dev/.jbang/cache/urls/464f1a7af0d976aa0f24236c65853a68126a2e732cd2d2a477f372a34f99a836/start-symja.jsh`

This is the content:

```
dev@DESKTOP-6LF86RL:~$ cat /home/dev/.jbang/cache/urls/464f1a7af0d976aa0f24236c65853a68126a2e732cd2d2a477f372a34f99a836/
start-symja.jsh
//DEPS org.matheclipse:matheclipse-core:2.0.0,org.matheclipse:matheclipse-io:2.0.0
import java.io.*;
import java.math.*;
import java.net.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.*;
import java.util.prefs.*;
import java.util.regex.*;
import java.util.stream.*;
import org.matheclipse.io.eval.*;
import org.matheclipse.core.expression.*;
import org.matheclipse.core.eval.*;
import org.matheclipse.core.interfaces.*;
import static org.matheclipse.core.expression.F.*;

ExprEvaluator ev = new ExprEvaluator();dev@DESKTOP-6LF86RL:~$
```

**Comment by quintesse** [comment]
The problem here is your [catalog](https://github.com/axkr/jbang-catalog/blob/master/jbang-catalog.json), specifically these 4 lines:

```
      "repositories": [
        "org.matheclipse:matheclipse-core:2.0.0",
        "org.matheclipse:matheclipse-io:2.0.0"
      ]
```

The `repositories` item is for custom Maven repositories, not dependencies. Just remove those lines and things will work.

Closing.

**Comment by axkr** [comment]
Seems that my  0.93.0 doesn't use the latest GIT version? Does this make a difference?

```
dev.jbang.dependencies.MavenRepo.apply(MavenRepo.java:32)
```

https://github.com/jbangdev/jbang/blob/acf41460dec7e974a8f8afa26d0329d9f30d7978/src/main/java/dev/jbang/dependencies/MavenRepo.java#L32

**Comment by quintesse** [comment]
Hi @axkr , that code hasn't been released yet but shouldn't affect this issue. It's really nothing more than those wrong lines in the .json file.

**Comment by axkr** [comment]
Installed 0.94.0 now 

This command line works without problems under WSL Ubuntu :partying_face:
```
jbang --deps org.matheclipse:matheclipse-io:2.0.0 -s https://github.com/axkr/symja_android_librar
y/blob/master/symja_android_library/start-symja.jsh -i
```

But there's no change with the `invalid URL`problem:

```
dev@DESKTOP-6LF86RL:~$ jbang --verbose symjajsh@axkr
[jbang] jbang version 0.94.0
[jbang] Reading catalog from /home/dev/.jbang/implicit-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/axkr/jbang-catalog/HEAD/jbang-catalog.json = /home/dev/.jbang/cache/urls/cba52fbe16567e383c98a35ac557a18209bfad578dbf255a70ce2bf41ac02f40/jbang-catalog.json
[jbang] Reading catalog from /home/dev/.jbang/cache/urls/cba52fbe16567e383c98a35ac557a18209bfad578dbf255a70ce2bf41ac02f40/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/axkr/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Duplicating classpath resource jbang-catalog.json
[jbang] Reading catalog from /home/dev/.jbang/cache/urls/2c97f3a787487bf73b7f4d02e109487e0e43be594ef95072827efd1500cd99ae
[jbang] Retrieved file from cache https://raw.githubusercontent.com/axkr/symja_android_library/master/symja_android_library/start-symja.jsh = /home/dev/.jbang/cache/urls/464f1a7af0d976aa0f24236c65853a68126a2e732cd2d2a477f372a34f99a836/start-symja.jsh
[jbang] Repositories: null=org.matheclipse:matheclipse-core:2.0.0, null=org.matheclipse:matheclipse-io:2.0.0
[jbang] Resolving dependencies...
[jbang] [ERROR] invalid URL
java.lang.IllegalArgumentException: invalid URL
        at org.jboss.shrinkwrap.resolver.api.maven.repository.MavenRemoteRepositories.createRemoteRepository(MavenRemoteRepositories.java:45)
        at dev.jbang.dependencies.MavenRepo.apply(MavenRepo.java:36)
        at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$2(DependencyUtil.java:161)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:161)
        at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:131)
        at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:77)
        at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:67)
        at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:363)
        at dev.jbang.source.generators.JshCmdGenerator.generateCommandLineList(JshCmdGenerator.java:35)
        at dev.jbang.source.generators.BaseCmdGenerator.generate(BaseCmdGenerator.java:35)
        at dev.jbang.cli.Run.doCall(Run.java:103)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:93)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.JBang$3.handle(JBang.java:145)
        at dev.jbang.cli.JBang$3.handle(JBang.java:140)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: java.net.MalformedURLException: unknown protocol: org.matheclipse
        at java.base/java.net.URL.<init>(URL.java:652)
        at java.base/java.net.URL.<init>(URL.java:541)
        at java.base/java.net.URL.<init>(URL.java:488)
        at org.jboss.shrinkwrap.resolver.api.maven.repository.MavenRemoteRepositories.createRemoteRepository(MavenRemoteRepositories.java:42)
        ... 22 more
```

**Comment by axkr** [comment]
Added another alias which works correctly:
- https://github.com/axkr/jbang-catalog/blob/master/jbang-catalog.json

```
jbang helloSymja@axkr
```

**Comment by maxandersen** [comment]
Nice. That works as java don't need classpath on command line.
