### ISSUE TITLE
Native Image has Error: --class-path= requires class path specification

### ISSUE THREAD

**Issue by murphye** [jbangdev/jbang#140]
```
eric@MacBook-Pro-7 jbang % jbang --version
0.32.0
```

```
eric@MacBook-Pro-7 jbang % java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```

```
eric@MacBook-Pro-7 jbang % jbang -n --verbose helloworld.java
[jbang] native-image: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.1.0/Contents/Home/bin/native-image -H:+ReportExceptionStackTraces --enable-https --class-path= -jar /Users/eric/.jbang/cache/jars/helloworld.java.c4c4e76c952806b74722a1af8bf80a5e9cfa6aa5ff679fc22955937f31d78e91.jar /Users/eric/.jbang/cache/jars/helloworld.java.c4c4e76c952806b74722a1af8bf80a5e9cfa6aa5ff679fc22955937f31d78e91.jar.bin
[jbang] log: /var/folders/yh/v3dr95n52nl19yc58vk64f4w0000gp/T/jbang12962813716642858166native-image
Error: --class-path= requires class path specification
dk.xam.jbang.ExitException: Error during native-image
	at dk.xam.jbang.Main.build(Main.java:492)
	at dk.xam.jbang.Main.doCall(Main.java:324)
	at dk.xam.jbang.Main.call(Main.java:378)
	at dk.xam.jbang.Main.call(Main.java:73)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at dk.xam.jbang.Main.main(Main.java:204)
```

**Comment by murphye** [comment]
Cool project btw!

**Comment by maxandersen** [comment]
ah - looks like not handling native well when zero dependencies! yeah we should fix that. you can "workaround" it just adding a `//DEPS <somethng>` :)

**Comment by maxandersen** [comment]
fixed in master now.
