### ISSUE TITLE
Disco API v2 is returning 404 when trying to download jdks

### ISSUE THREAD

**Issue by andreaTP** [jbangdev/jbang#1401]
**Describe the bug**
Starting jbang with a JDK non directly available always fails with:
```
Unable to download or install JDK version
```

Since `discoapi` is failing for v2.

**To Reproduce**
- `jbang init main.java`
- add as a second line `//JAVA 19` and make sure that Java 19 is not available on the current PATH
- jbang --verbose main.java
fails with:

```
[jbang] jbang version 0.95.0
[jbang] Build required as /Users/aperuffo/.jbang/cache/jars/main.java.88cf3be1c151ba55f47e473664fb78ccd7d2851aa37a038646157510ca0e773c.jar not readable or not found.
[jbang] System Java version detected as 11
[jbang] System Java version 11 incompatible, using JBang managed version 19
[jbang] Downloading JDK 19. Be patient, this can take several minutes...
[jbang] Downloading https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=19&architecture=x64&latest=available
[jbang] [ERROR] Required Java version not possible to download or install. You can run with '--java 11' to force using the default installed Java.
[jbang] Deleting folder /Users/aperuffo/.jbang/cache/jars/main.java.88cf3be1c151ba55f47e473664fb78ccd7d2851aa37a038646157510ca0e773c.jar.tmp
[jbang] [ERROR] Unable to download or install JDK version 19
dev.jbang.cli.ExitException: Unable to download or install JDK version 19
        at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:153)
        at dev.jbang.net.JdkManager.getInstalledJdk(JdkManager.java:114)
        at dev.jbang.net.JdkManager.getCurrentJdk(JdkManager.java:107)
        at dev.jbang.util.JavaUtil.resolveInJavaHome(JavaUtil.java:163)
        at dev.jbang.source.builders.JavaBuilder.getCompilerBinary(JavaBuilder.java:16)
        at dev.jbang.source.builders.BaseBuilder.compile(BaseBuilder.java:133)
        at dev.jbang.source.builders.BaseBuilder.build(BaseBuilder.java:108)
        at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:48)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:126)
        at dev.jbang.cli.Run.doCall(Run.java:97)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:136)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.JBang$3.handle(JBang.java:145)
        at dev.jbang.cli.JBang$3.handle(JBang.java:140)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download at https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=19&architecture=x64&latest=available. Server replied HTTP code: 404
        at dev.jbang.util.Util.downloadFile(Util.java:655)
        at dev.jbang.util.Util.downloadFile(Util.java:575)
        at dev.jbang.util.Util.downloadFileAndCache(Util.java:764)
        at dev.jbang.util.Util.downloadAndCacheFile(Util.java:736)
        at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:129)
        ... 20 more
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**Expected behavior**
Java 19 is downloaded and used.

**JBang version**
`0.95.0`

**Additional context**
I opened a relevant issue in the `discoapi` repo: https://github.com/foojayio/discoapi/issues/60

**Comment by andreaTP** [comment]
Additional context the corresponding V3 API call should be something similar to:

```
https://api.foojay.io/disco/v3.0/packages?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=19&release_status=ea,ga&architecture=x64&latest=available
```
note the additional `release_status=ea,ga`.

But it doesn't return anymore a direct link and we should parse the resulting json.

**Comment by maxandersen** [comment]
This sounds more like a breaking change In disco that should be fixed rather than we change it ?

**Comment by andreaTP** [comment]
Fixed as detailed in https://github.com/foojayio/discoapi/issues/60
