### ISSUE TITLE
 ConcurrentModificationException with --repos from the cli while running info tools

### ISSUE THREAD

**Issue by jmini** [jbangdev/jbang#1409]
**Describe the bug**
When you use `--repos mavencentral` in the command line, you get a `ConcurrentModificationException` when you run `info tools`

> **Note**
> Our use case is not use `mavencentral` but our company mirror of maven central. But for the reproducer I thought it is easier to use `mavencentral`, because everybody has it.

This is similar to https://github.com/jbangdev/jbang/issues/1377 but the command is not the same `info tools` instead of `run`.

**To Reproduce**

Create a small jbang script `log.java`:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS log4j:log4j:1.2.17

import static java.lang.System.out;

import org.apache.log4j.Logger;
import org.apache.log4j.BasicConfigurator;

import java.util.Arrays;

class log {

    static final Logger logger = Logger.getLogger(log.class);

    public static void main(String[] args) {
        BasicConfigurator.configure();
        logger.info("Welcome to jbang");

        Arrays.asList(args).forEach(arg -> logger.warn("arg: " + arg));
        logger.info("Hello from Java!");
    }
}
```

Run it with:
```
 jbang --verbose info tools --fresh --repos mavencentral log.java
```

Usage of `--fresh` make the error appear all the time.
Without `--fresh` it depends (and I could not yet figure out when it isn't working)

jbang is failing with:
```
[jbang] [ERROR] public class java.util.ConcurrentModificationException
```
(see the verbose output at the bottom)

**Expected behavior**
It should work.

**JBang version**

* `0.91.0` 🟢 --> works
* `0.92.0` 🔴 --> first version where this is broken
* `0.92.1` 🔴 --> broken
* `0.92.2` 🔴 --> broken
* `0.93.0` 🔴 --> broken
* `0.94.0` 🔴 --> broken
* `0.95.0` 🔴 --> broken
* `0.96.0` 🔴 --> still broken with `info tools`, 🟢 `run` is working.

**Additional context**
Verbose output:
```
[jbang] jbang version 0.96.0
[jbang] System Java version detected as 8
[jbang] System Java version matches requested version 8
[jbang] Repositories: mavencentral=https://repo1.maven.org/maven2/, mavencentral=https://repo1.maven.org/maven2/
[jbang] Resolving dependencies...
[jbang] [ERROR] public class java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.addRemoteRepo(MavenWorkingSessionImpl.java:315)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:71)
	at org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemImpl.withRemoteRepo(ConfigurableMavenResolverSystemImpl.java:36)
	at dev.jbang.dependencies.MavenRepo.apply(MavenRepo.java:40)
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$2(DependencyUtil.java:161)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:161)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:131)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:77)
	at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:68)
	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:318)
	at dev.jbang.cli.BaseInfoCommand$ScriptInfo.<init>(Info.java:92)
	at dev.jbang.cli.BaseInfoCommand.getInfo(Info.java:157)
	at dev.jbang.cli.Tools.doCall(Info.java:181)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:136)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.JBang$3.handle(JBang.java:145)
	at dev.jbang.cli.JBang$3.handle(JBang.java:140)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

I think the main issue is that the same repo is added twice in the `[jbang] Repositories` line.

This is similar to this issue https://github.com/jbangdev/jbang/issues/1377

**Comment by maxandersen** [comment]
i can confirm i see it. investigating.

**Comment by maxandersen** [comment]
so issue is that somehow resolve is called twice and mavencentral ends up getting added twice...which in itself does not seem to cause the concurrent modification...as i I can't actually reproduce that in a unit test (at least not yet)

**Comment by maxandersen** [comment]
@quintesse any idea? looks like a possible outcome of the command refactoring on how it deals with runcontext.

**Comment by quintesse** [comment]
Hmm I can't seem to reproduce this. Both 0.95 and 0.96 just worked for me. Will keep on trying...

**Comment by quintesse** [comment]
I still can't reproduce it the way it was described in this issue but I can do it very simply like this:

```
jbang --verbose info tools --fresh --repos mavencentral --repos mavencentral log.java
```

**Comment by quintesse** [comment]
Ha, the underlying problem is actually a bug in Shrinkwrap:

[org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java](https://github.com/shrinkwrap/resolver/blob/master/maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/MavenWorkingSessionImpl.java#L315)

```java
for (RemoteRepository r : this.additionalRemoteRepositories) {
    if (r.getId().equals(repository.getId())) {
        this.additionalRemoteRepositories.remove(r);
    }
}
```

Given the fact that the code hasn't been updated in years I don't think trying to get upstream to fix this will work. (I guess we really need to think about replacing that library).

**Comment by maxandersen** [comment]
...or simply not add same repo twice as old code didn't do :)

**Comment by quintesse** [comment]
Sure, I'm just pointing out that the underlying reason is a bug upstream. In the way it was supposed to work there shouldn't be any problem adding the same repo twice.

**Comment by quintesse** [comment]
@jmini this should be fixed now in the latest release, can you confirm?
