### ISSUE TITLE
can no longer download java 19

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1458]
```
jbang --verbose jdk install 19
[jbang] jbang version 0.98.0.7
[jbang] Downloading JDK 19. Be patient, this can take several minutes...
[jbang] Downloading https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=19&architecture=x64&latest=available
[jbang] System Java version detected as 11
[jbang] [ERROR] Required Java version not possible to download or install. You can run with '--java 11' to force using the default installed Java.
[jbang] [ERROR] Unable to download or install JDK version 19
dev.jbang.cli.ExitException: Unable to download or install JDK version 19
	at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:153)
	at dev.jbang.cli.Jdk.install(Jdk.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download at https://api.foojay.io/disco/v2.0/directuris?distro=temurin&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=19&architecture=x64&latest=available. Server replied HTTP code: 404
	at dev.jbang.util.Util.downloadFile(Util.java:656)
	at dev.jbang.util.Util.downloadFile(Util.java:576)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:765)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:737)
	at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:129)
	... 15 more
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**Comment by quintesse** [comment]
Perhaps a regression again in the Disco API?

**Comment by maxandersen** [comment]
Disco updated their api to return EA if No GA Available.
