### ISSUE TITLE
Expose response headers / and or payload when non 4xx HTTP call is returned

### ISSUE THREAD

**Issue by bric3** [jbangdev/jbang#1466]
**Is your feature request related to a problem? Please describe.**

I was hitting this gist url, but got a 403 response, so I wasn't able 

```shell
$ jbang https://gist.github.com/bric3/2338aad81b5bba614020a17a1fd0884f
[jbang] [ERROR] java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
[jbang] Run with --verbose for more details
```

Even running with `--verbose` won't produce interesting details, it's a stacktrace. Here the interesting stuff is the response header and/or payload

<details><summary>exception stackframe</summary>

```
[jbang] jbang version 0.98.0
[jbang] Gist url api: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
[jbang] Reading JSON from: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
[jbang] Error when extracting file from gist url.
[jbang] [ERROR] java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
java.lang.IllegalStateException: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
        at dev.jbang.util.Util.extractFileFromGist(Util.java:952)
        at dev.jbang.util.Util.swizzleURL(Util.java:839)
        at dev.jbang.source.resolvers.RemoteResourceResolver.fetchScriptFromUntrustedURL(RemoteResourceResolver.java:52)
        at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
        at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
        at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
        at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:37)
        at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
        at dev.jbang.source.RunContext.resolveChecked(RunContext.java:343)
        at dev.jbang.source.RunContext.forResource(RunContext.java:338)
        at dev.jbang.cli.Run.doCall(Run.java:95)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:136)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at dev.jbang.cli.JBang$3.handle(JBang.java:151)
        at dev.jbang.cli.JBang$3.handle(JBang.java:146)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/gists/2338aad81b5bba614020a17a1fd0884f
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at dev.jbang.util.Util.readJsonFromURL(Util.java:1026)
        at dev.jbang.util.Util.extractFileFromGist(Util.java:949)
        ... 31 more
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
[jbang] Redirected to: https://github.com/jbangdev/jbang/releases/latest/download/version.txt
```

</details>

**Describe the solution you'd like**

So actually hitting this API you got the reason why this doesn't work, I believe that the verbose mode should at least show response header and/or payload. And even better the default mode could maybe understand the header `x-ratelimit-*` headers to show a nicer output. Possibly 429 HTTP status too.

```
HTTP/2 403 
date: Thu, 22 Sep 2022 12:03:11 GMT
server: Varnish
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-security-policy: default-src 'none'; style-src 'unsafe-inline'
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
content-type: application/json; charset=utf-8
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 60
x-ratelimit-remaining: 0
x-ratelimit-reset: 1663849268
x-ratelimit-resource: core
x-ratelimit-used: 60
content-length: 279
x-github-request-id: FC73:644B:43647F2:44817FD:632C4EFF

{"message":"API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Describe alternatives you've considered**
To learn about the 403 I ran the `curl -i ....` myself.

**Additional context**

**Comment by quintesse** [comment]
Sounds like a good idea 👍

**Comment by bric3** [comment]
So looking at the code it seems the code is relying on `new URL(requestUrl).openConnection()`.

https://github.com/bric3/jbang/blob/6218b6faf8fac470258b976bc1767017fa268efe/src/main/java/dev/jbang/util/Util.java#L1026

Unfortunately `HttpURLConnection` does only emit an `IOException`, and does allow to retrieve individual elements of the response, such the status code, and we can forgive headers or payload as well. And I suppose the same apply to other (as in non gist) http based downloader.

Given the project can run on Java 8, in order to implement this it means adding a featured http client dependency. This might be helpful for connection pooling and compression too.
But this will add some weight to jbang.
