### ISSUE TITLE
Unknown option: '--preview'

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#1609]
Tested with 0.106.1, seems like the --preview flag 
https://github.com/jbangdev/jbang/blob/8516294243004f4c0286ae578cbe964c76f5fce3/src/main/java/dev/jbang/cli/JBang.java#L58

isn't recognized: 

 ```
➜  which jbang
/Users/fbricon/.sdkman/candidates/jbang/current/bin/jbang
➜  jbang --version
0.106.1
➜  jbang init --preview  gh.java "connect to github an fetch all repositories under jbangdev and collect how many stars they have"
Unknown option: '--preview'
Usage: jbang init -o [-h] [--edit] [--force] --fresh [--insecure] --quiet
                  --verbose [--config=<config>] [-t=<initTemplate>]
                  [-D=<String=Object>]... [--deps=<dependencies>]...
                  scriptOrFile [params...]
Initialize a script.
      scriptOrFile        A file or URL to a Java code file
      [params...]         Parameters to pass on to the generation
      --config=<config>   Path to config file to be used instead of the default
  -D=<String=Object>      set a system property
      --deps=<dependencies>
                          Add additional dependencies (Use commas to separate
                            them).
      --edit              Open editor on the generated file(s)
      --force             Force overwrite of existing files
      --fresh             Make sure we use fresh (i.e. non-cached) resources.
  -h, --help              Display help/info. Use 'jbang <command> -h' for
                            detailed usage.
      --insecure          Enable insecure trust of all SSL certificates.
  -o, --offline           Work offline. Fail-fast if dependencies are missing.
                            No connections will be attempted
      --quiet             jbang will be quiet, only print when error occurs.
  -t, --template=<initTemplate>
                          Init script with a java class useful for scripting
      --verbose           jbang will be verbose on what it does.
 ```

**Comment by fbricon** [comment]
I tried moving my `~/.jbang` directory but it didn't work wither

**Comment by fbricon** [comment]
The gpt templates are listed, but the actual templates are missing
```
➜ jbang template list
agent = Agent template
cli = CLI template
gpt = Template using ChatGPT (requires --preview and OPENAI_API_KEY)
gpt.groovy = Template using ChatGPT for groovy (requires --preview and OPENAI_API_KEY)
gpt.kt = Template using ChatGPT for kotlin (requires --preview and OPENAI_API_KEY)
hello = Basic Hello World template
hello.groovy = Basic groovy Hello World template
hello.kt = Basic kotlin Hello World template
qcli = Quarkus CLI template
qmetrics = Quarkus Metrics template
qrest = Quarkus REST template
readme.md = Basic markdown readme template
➜  jbang init -t gpt gh.java
[jbang] [ERROR] Resource not found on class path: init-gpt.java.qute
[jbang] Run with --verbose for more details
```

**Comment by maxandersen** [comment]
jbang --preview init. Preview is a global flag.

**Comment by fbricon** [comment]
Fair enough. Although documentation is incomplete in https://github.com/jbangdev/jbang/releases/tag/v0.106.0

On the other hand, it fails when running:

```
jbang --verbose  --preview  init gh.java "connect to github an fetch all repositories under jbangdev and collect how many stars they have"
[jbang] [0:257] jbang version 0.106.1
[jbang] [0:267] Reading catalog from classpath:/jbang-catalog.json
[jbang] [0:296] JBangGPT Preview activated
[jbang] [0:296] [WARN] The result can vary greatly. Sometimes it works - other times it is just for inspiration or a good laugh.
[jbang] [0:581] ChatGPT prompt {temperature=0.8, messages=[{role=system, content=You are to generate a response that only contain code that is written in a file ending in java in the style of jbang. The main class must be named gh . Add no additional text.You can put comments in the code.}, {role=user, content=connect to github an fetch all repositories under jbangdev and collect how many stars they have}], model=gpt-3.5-turbo}
[jbang] [0:722] [ERROR] Cannot invoke "java.util.List.stream()" because "result.choices" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "result.choices" is null
	at dev.jbang.cli.Init.fetchGptResponse(Init.java:221)
	at dev.jbang.cli.Init.doCall(Init.java:92)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [0:724] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

But that's another problem

**Comment by maxandersen** [comment]
Hmmm...wonder if You are getting an error back from chatgpt and we dont handle that error condition?

**Comment by fbricon** [comment]
https://github.com/jbangdev/jbang/blob/8516294243004f4c0286ae578cbe964c76f5fce3/src/main/java/dev/jbang/cli/Init.java#L221 shows a response was received, but with unexpected content. Would be helpful if the GPT response was part of the verbose output
