### ISSUE TITLE
NPE in Init.fetchGptResponse ("result.choices" is null)

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#1610]
As mentioned in https://github.com/jbangdev/jbang/issues/1609#issuecomment-1501200763, JBang fails with an NPE in 
https://github.com/jbangdev/jbang/blob/8516294243004f4c0286ae578cbe964c76f5fce3/src/main/java/dev/jbang/cli/Init.java#L221

when trying the GPT preview feature:

```
jbang --verbose  --preview  init gh.java "connect to github an fetch all repositories under jbangdev and collect how many stars they have"
[jbang] [0:257] jbang version 0.106.1
[jbang] [0:267] Reading catalog from classpath:/jbang-catalog.json
[jbang] [0:296] JBangGPT Preview activated
[jbang] [0:296] [WARN] The result can vary greatly. Sometimes it works - other times it is just for inspiration or a good laugh.
[jbang] [0:581] ChatGPT prompt {temperature=0.8, messages=[{role=system, content=You are to generate a response that only contain code that is written in a file ending in java in the style of jbang. The main class must be named gh . Add no additional text.You can put comments in the code.}, {role=user, content=connect to github an fetch all repositories under jbangdev and collect how many stars they have}], model=gpt-3.5-turbo}
[jbang] [0:722] [ERROR] Cannot invoke "java.util.List.stream()" because "result.choices" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "result.choices" is null
	at dev.jbang.cli.Init.fetchGptResponse(Init.java:221)
	at dev.jbang.cli.Init.doCall(Init.java:92)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [0:724] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

After logging the response output, I see why:
```
[jbang] [0:707] ChatGPT response: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

So json deserialization doesn't take response errors into account.

The weird thing is I never used that OPENAI_API_KEY before, the web UI works without an quota issues.

**Comment by maxandersen** [comment]
Yeah. I have a subskription so didnt see that kind of error. 

You want to do a pr to handle errors better like this?

**Comment by fbricon** [comment]
Yeah so my free-trial expired on April 1st, 2023, so I won't be able to try Open AI API calls, as I don't plan on subscribing.

What is JBang supposed to do in case of a ChatGPT error? stop? or fallback to non-gpt file generation?

**Comment by maxandersen** [comment]
Error I would say as user entered a prompt.
