### ISSUE TITLE
 Can't find resource for bundle dev.jbang.cli.JBang$ConfigurationResourceBundle, key preview

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1614]
Get this error: 

```
[jbang] [0:417] jbang version 0.106.1.2
[jbang] [0:438] [ERROR] Can't find resource for bundle dev.jbang.cli.JBang$ConfigurationResourceBundle, key preview
java.util.MissingResourceException: Can't find resource for bundle dev.jbang.cli.JBang$ConfigurationResourceBundle, key preview
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at picocli.CommandLine$Model$Messages.addAllWithPrefix(CommandLine.java:11402)
	at picocli.CommandLine$Model$Messages.getStringArray(CommandLine.java:11398)
	at picocli.CommandLine$Model$ArgSpec.description(CommandLine.java:8719)
	at picocli.CommandLine$Help$DefaultOptionRenderer.renderDescriptionLines(CommandLine.java:16223)
	at picocli.CommandLine$Help$DefaultOptionRenderer.render(CommandLine.java:16196)
	at picocli.CommandLine$Help.calcLongOptionColumnWidth(CommandLine.java:16022)
	at picocli.CommandLine$Help.createDefaultLayout(CommandLine.java:16000)
	at picocli.CommandLine$Help.createDefaultLayout(CommandLine.java:15991)
	at picocli.CommandLine$Help.parameterList(CommandLine.java:15655)
	at picocli.CommandLine$Help.parameterList(CommandLine.java:15645)
	at picocli.CommandLine$Model$UsageMessageSpec$10.render(CommandLine.java:7856)
	at picocli.CommandLine.usage(CommandLine.java:2682)
	at picocli.CommandLine.usage(CommandLine.java:2654)
	at picocli.CommandLine.usage(CommandLine.java:2610)
	at dev.jbang.cli.JBang.doCall(JBang.java:98)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [0:439] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

I have this in config:
```
 jbang config list
format = text
init.template = hello
jdkproviders = current,default,javahome,path,jbang
preview = true
run.debug = 4004
run.jfr = filename={baseName}.jfr
wrapper.install.dir = .
```

preview might not be known but shouldn't error here - at most warn ?

**Comment by quintesse** [comment]
But what command did you run? Because there error is in PicoCli code.

**Comment by maxandersen** [comment]
Just 'jbang'

**Comment by quintesse** [comment]
Ah wait, it's for an option that's part of a PicoCli annotation, right?
Indeed, adding the "preview" option to the https://github.com/jbangdev/jbang/blob/main/src/main/resources/jbang.properties file is not optional, you are required to add it. And because options in this file can never be deleted, it's safe.
