### ISSUE TITLE
[build native image on windows]Fatal error: java.lang.IllegalArgumentException: 'other' has different root

### ISSUE THREAD

**Issue by lost22git** [jbangdev/jbang#1616]
**Describe the bug**
jbang build native image on windows throw an error as follow

`Fatal error: java.lang.IllegalArgumentException: 'other' has different root`

**To Reproduce**
1. jbang init bug.java
2. jbang run -n bug.java

**Expected behavior**
throw an error：`Fatal error: java.lang.IllegalArgumentException: 'other' has different root`

**JBang version**
Paste output of `jbang version --verbose`
0.106.3

**Additional context**
```
╰─❯ java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)
╰─❯ cl --version
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
╰─❯ jbang --version
0.106.3
╰─❯ jbang init bug.java
[jbang] File initialized. You can now run it with 'jbang bug.java' or edit it using 'jbang edit --open=[editor] bug.java' where [editor] is your editor or IDE, e.g. 'code'. If your IDE supports JBang, you can edit the directory instead: 'jbang edit . 'bug.java. See https://jbang.dev/ide
╰─❯ cat bug.java
///usr/bin/env jbang "$0" "$@" ; exit $?


import static java.lang.System.*;

public class bug {

    public static void main(String... args) {
        out.println("Hello World");
    }
}
╰─❯ jbang --verbose run -n bug.java
[jbang] [0:266] jbang version 0.106.3
[jbang] [0:283] Resolving resource ref: bug.java
[jbang] [0:289] Resolved resource ref as: bug.java (cached as: E:\code\me\bug\bug.java)
[jbang] [0:329] Building as native build required.
[jbang] [0:332] Looking for JDK: 0
[jbang] [0:337] Using JDK: 19 (19.0.1, current, E:\scoop\global\apps\graalvm\current)
[jbang] [0:376] Building jar...
[jbang] [0:377] Compile: E:\scoop\global\apps\graalvm\current\bin\javac.exe -g -d C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\classes E:\code\me\bug\bug.java
[jbang] [0:808] Looking for JDK: 0
[jbang] [0:808] Using JDK: 19 (19.0.1, current, E:\scoop\global\apps\graalvm\current)
[jbang] [0:850] Looking for JDK: 0
[jbang] [0:850] Using JDK: 19 (19.0.1, current, E:\scoop\global\apps\graalvm\current)
[jbang] [0:851] Package: E:\scoop\global\apps\graalvm\current\bin\jar.exe cfme C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\bug.jar C:\Users\zzz\AppData\Local\Temp\jbang-manifest8321857376262122328mf bug -C C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\classes .
[jbang] [1:026] Deleting file C:\Users\zzz\AppData\Local\Temp\jbang-manifest8321857376262122328mf
[jbang] [1:026] Deleting folder C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\classes
[jbang] [1:029] Deleting folder C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\generated
[jbang] [1:030] native-image: E:\scoop\global\apps\graalvm\current\bin\native-image.cmd -H:+ReportExceptionStackTraces --enable-https -jar C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\bug.jar C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\bug
[jbang] [1:031] log: C:\Users\zzz\AppData\Local\Temp\jbang8008773056626735670native-image
Fatal error: java.lang.IllegalArgumentException: 'other' has different root
        at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:420)
        at java.base/sun.nio.fs.WindowsPath.relativize(WindowsPath.java:42)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.lambda$reportBuildArtifacts$10(ProgressReporter.java:676)
        at java.base/java.util.Map.forEach(Map.java:716)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.lambda$reportBuildArtifacts$11(ProgressReporter.java:669)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.reportImpl(ReportUtils.java:154)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.reports.ReportUtils.report(ReportUtils.java:140)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.reportBuildArtifacts(ProgressReporter.java:679)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printArtifacts(ProgressReporter.java:647)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ProgressReporter.printEpilog(ProgressReporter.java:613)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:462)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Error: Image build request failed with exit status 1
[jbang] [36:183] [ERROR] Error during native-image
dev.jbang.cli.ExitException: Error during native-image
        at dev.jbang.source.buildsteps.NativeBuildStep.runNativeBuilder(NativeBuildStep.java:91)
        at dev.jbang.source.buildsteps.NativeBuildStep.build(NativeBuildStep.java:51)
        at dev.jbang.source.buildsteps.NativeBuildStep.build(NativeBuildStep.java:24)
        at dev.jbang.source.AppBuilder.build(AppBuilder.java:114)
        at dev.jbang.source.AppBuilder.build(AppBuilder.java:22)
        at dev.jbang.cli.Run.doCall(Run.java:95)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at dev.jbang.cli.JBang$3.handle(JBang.java:147)
        at dev.jbang.cli.JBang$3.handle(JBang.java:142)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] [36:185] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
// ------------------------------------------------ run it again 
╰─❯ jbang --verbose run -n bug.java
[jbang] [0:271] jbang version 0.106.3
[jbang] [0:287] Resolving resource ref: bug.java
[jbang] [0:292] Resolved resource ref as: bug.java (cached as: E:\code\me\bug\bug.java)
[jbang] [0:376] Looking for JDK: 0
[jbang] [0:380] Using JDK: 19 (19.0.1, current, E:\scoop\global\apps\graalvm\current)
[jbang] [0:381] No build required. Reusing jar from C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\bug.jar
[jbang] [0:382] run: C:\Users\zzz\.jbang\cache\jars\bug.java.5a0978ac833ecc8177a899a0e2f6901d4453baffa1399564550ac7d1dd6d8198\bug.exe
Hello World
```

**Comment by lost22git** [comment]
https://github.com/oracle/graal/blob/a475260832933c6cff41ffd9f224e0171fd4f815/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/ProgressReporter.java#L676 

Looks like getting artifact relative paths failed during build_artifacts.txt file generation (due to artifact path and buildDir path are in different partitions)

The buildDir path defaults to CWD when the -H:Path option is not specified

Something lie this:
```java
jshell> var executableFile = Paths.get("c:/Users/zzz/.jbang/cache/jars/xxx.exe")
executableFile ==> c:\Users\zzz\.jbang\cache\jars\xxx.exe

jshell> var buildDir = Paths.get("e:/code")
buildDir ==> e:\code

jshell> buildDir.relativize(executableFile)
|  Exception java.lang.IllegalArgumentException: 'other' has different root
|        at WindowsPath.relativize (WindowsPath.java:420)
|        at WindowsPath.relativize (WindowsPath.java:42)
|        at (#3:1)

```

Maybe jbang can add -H:Path=\<jbang buildDir\> when generating the native-image command?

Graalvm seems to have a pr related to this (https://github.com/oracle/graal/pull/5441)

Finally I will close this issue, because it is an issue of graalvm and may be fixed in a new version.
