### ISSUE TITLE
Unable to install camel using jbang in Ubuntu

### ISSUE THREAD

**Issue by pjankolibaincapital** [jbangdev/jbang#1628]
**Describe the bug**
I keep failing to install camel cli using jbang. I am following the steps on https://camel.apache.org/manual/getting-started.html

**To Reproduce**
1. curl -Ls https://sh.jbang.dev | bash -s - trust add https://github.com/apache/
2. curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force camel@apache/camel

**Expected behavior**
I expected to get camel cli installed using jbang

**JBang version**
Paste output of `jbang version --verbose`
[jbang] [0:706] jbang version 0.107.0
Cache: /home/pjankoli/.jbang/cache
Config: /home/pjankoli/.jbang
Repository:/home/pjankoli/.m2/repository
0.107.0

![Camel using Jbang](https://github.com/jbangdev/jbang/assets/135765844/6ab692dc-ba27-403e-a3e1-97afccef2de5)

**Comment by quintesse** [comment]
Thanks for the report @pjankolibaincapital , but can you copy & paste the full error?

**Comment by pjankolibaincapital** [comment]
jbang] [0:585] jbang version 0.107.0
[jbang] [0:592] Resolving resource ref: camel@apache/camel
[jbang] [0:611] Reading catalog from classpath:/jbang-catalog.json
[jbang] [0:682] Local catalog 'apache/camel' not found, trying implicit catalogs...
[jbang] [0:917] Requesting HTTP GET https://raw.githubusercontent.com/apache/camel/HEAD/jbang-catalog.json
[jbang] [0:918] Headers {User-Agent=[JBang/0.107.0 (Linux/5.15.0-1019-aws/amd64) Java/17.0.7/Eclipse Adoptium]}
[jbang] [1:104] No catalog found at https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:118)
	at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
	at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:93)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$2(ImplicitCatalogRef.java:76)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:87)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:66)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:258)
	at dev.jbang.catalog.Alias.merge(Alias.java:184)
	at dev.jbang.catalog.Alias.get(Alias.java:149)
	at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	at dev.jbang.cli.AppInstall.install(App.java:108)
	at dev.jbang.cli.AppInstall.doCall(App.java:88)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at dev.jbang.util.Util.handleRedirects(Util.java:1071)
	at dev.jbang.util.Util.access$400(Util.java:73)
	at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:890)
	at dev.jbang.util.Util.connect(Util.java:812)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:741)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:692)
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:115)
	... 50 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 74 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 79 more
[jbang] [1:111] Requesting HTTP GET https://gitlab.com/apache/camel/-/raw/HEAD/jbang-catalog.json
[jbang] [1:111] Headers {User-Agent=[JBang/0.107.0 (Linux/5.15.0-1019-aws/amd64) Java/17.0.7/Eclipse Adoptium]}
[jbang] [1:183] No catalog found at https://gitlab.com/apache/camel/-/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://gitlab.com/apache/camel/-/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:118)
	at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
	at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:93)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$4(ImplicitCatalogRef.java:79)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:87)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:66)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:258)
	at dev.jbang.catalog.Alias.merge(Alias.java:184)
	at dev.jbang.catalog.Alias.get(Alias.java:149)
	at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	at dev.jbang.cli.AppInstall.install(App.java:108)
	at dev.jbang.cli.AppInstall.doCall(App.java:88)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at dev.jbang.util.Util.handleRedirects(Util.java:1071)
	at dev.jbang.util.Util.access$400(Util.java:73)
	at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:890)
	at dev.jbang.util.Util.connect(Util.java:812)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:741)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:692)
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:115)
	... 50 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 74 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 79 more
[jbang] [1:207] Requesting HTTP GET https://bitbucket.org/apache/camel/raw/HEAD/jbang-catalog.json
[jbang] [1:207] Headers {User-Agent=[JBang/0.107.0 (Linux/5.15.0-1019-aws/amd64) Java/17.0.7/Eclipse Adoptium]}
[jbang] [1:282] No catalog found at https://bitbucket.org/apache/camel/src/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://bitbucket.org/apache/camel/src/HEAD/jbang-catalog.json
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:118)
	at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
	at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	at dev.jbang.catalog.ImplicitCatalogRef.tryDownload(ImplicitCatalogRef.java:93)
	at dev.jbang.catalog.ImplicitCatalogRef.lambda$getImplicitCatalogUrl$6(ImplicitCatalogRef.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.catalog.ImplicitCatalogRef.getImplicitCatalogUrl(ImplicitCatalogRef.java:87)
	at dev.jbang.catalog.CatalogRef.get(CatalogRef.java:66)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:143)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:258)
	at dev.jbang.catalog.Alias.merge(Alias.java:184)
	at dev.jbang.catalog.Alias.get(Alias.java:149)
	at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	at dev.jbang.cli.AppInstall.install(App.java:108)
	at dev.jbang.cli.AppInstall.doCall(App.java:88)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at dev.jbang.util.Util.handleRedirects(Util.java:1071)
	at dev.jbang.util.Util.access$400(Util.java:73)
	at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:890)
	at dev.jbang.util.Util.connect(Util.java:812)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:741)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:692)
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:115)
	... 50 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 74 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
	... 79 more
[jbang] [1:293] [ERROR] Unknown catalog 'apache/camel'
dev.jbang.cli.ExitException: Unknown catalog 'apache/camel'
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:147)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:258)
	at dev.jbang.catalog.Alias.merge(Alias.java:184)
	at dev.jbang.catalog.Alias.get(Alias.java:149)
	at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	at dev.jbang.cli.AppInstall.install(App.java:108)
	at dev.jbang.cli.AppInstall.doCall(App.java:88)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [1:294] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues

**Comment by maxandersen** [comment]
Do you have a proxy/firewall preventing downloads ?

**Comment by pjankolibaincapital** [comment]
We do have a firewall, but I am able to run other downloads with no issues. Another coworker was able to run this same command without any issues and we are running identical Ubuntu Amazon Workspaces.

**Comment by maxandersen** [comment]
somehow your JDK is not accepting the certificate provided by github:
```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

what java version are you running jbang with?

try run `java -version` in same place you are running `jbang`

**Comment by pjankolibaincapital** [comment]
This is what I have -
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

**Comment by maxandersen** [comment]
ok so recent enough java - but somehow your machine does not accept the certificate.
 try running with `jbang --insecure` then jbang will turn off validation but not sure that is enough for this specific certificate issue.

**Comment by pjankolibaincapital** [comment]
I ran sudo update-alternatives --config java and reselected my JDK and now it works
