### ISSUE TITLE
console read NPE's in container with no terminal associated

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#1653]
I'm trying to make a new docker image for jbang that is simpler than current jbang-action and hit this issue:

```
[jbang] [0:469] Type in your choice and hit enter. Will automatically select option (0) after 30 seconds.
[jbang] [0:472] [ERROR] public class java.lang.NullPointerException
java.lang.NullPointerException
        at dev.jbang.util.ConsoleInput.readLine(ConsoleInput.java:71)
        at dev.jbang.util.Util.askInput(Util.java:1774)
        at dev.jbang.source.resolvers.RemoteResourceResolver.fetchScriptFromUntrustedURL(RemoteResourceResolver.java:69)
        at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
        at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
```

simply running `jbang quarkusinfo@maxandersen` from within a container with no terminal.

we should not NPE.

**Comment by quintesse** [comment]
It's trying to print out an exception stacktrace by getting the "cause" which in this case is `null`.
But the real question is: why do we even get to that code? If there's no terminal we should already have detected that.
