### ISSUE TITLE
dev.jbang.cli.ExitException: Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json

### ISSUE THREAD

**Issue by cyongk** [jbangdev/jbang#1708]
command execute:jbang app install camel@apache/camel 

[jbang] [0:336] jbang version 0.113.0
[jbang] [0:348] Resolving resource ref: camel@apache/camel
[jbang] [0:353] Requesting HTTP GET https://www.jbang.dev/releases/latest/download/version.txt
[jbang] [0:353] Reading catalog from /Users/cyongk/.jbang/implicit-catalog.json
[jbang] [0:353] Headers {User-Agent=[JBang/0.113.0 (Mac OS X/13.4.1/x86_64) Java/17.0.2/Oracle Corporation]}
[jbang] [0:391] Requesting HTTP GET https://raw.githubusercontent.com/apache/camel/HEAD/jbang-catalog.json
[jbang] [0:391] Headers {User-Agent=[JBang/0.113.0 (Mac OS X/13.4.1/x86_64) Java/17.0.2/Oracle Corporation]}
[jbang] [0:394] [ERROR] Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:118)
	at dev.jbang.source.resolvers.RemoteResourceResolver.resolve(RemoteResourceResolver.java:42)
	at dev.jbang.source.resolvers.CombinedResourceResolver.lambda$resolve$0(CombinedResourceResolver.java:27)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at dev.jbang.source.resolvers.CombinedResourceResolver.resolve(CombinedResourceResolver.java:29)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:131)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	at dev.jbang.catalog.Catalog.getByName(Catalog.java:145)
	at dev.jbang.catalog.Alias.fromCatalog(Alias.java:274)
	at dev.jbang.catalog.Alias.merge(Alias.java:200)
	at dev.jbang.catalog.Alias.get(Alias.java:165)
	at dev.jbang.source.resolvers.AliasResourceResolver.resolve(AliasResourceResolver.java:39)
	at dev.jbang.source.ResourceResolver.resolve(ResourceResolver.java:52)
	at dev.jbang.source.ProjectBuilder.resolveChecked(ProjectBuilder.java:229)
	at dev.jbang.source.ProjectBuilder.build(ProjectBuilder.java:218)
	at dev.jbang.cli.AppInstall.install(App.java:108)
	at dev.jbang.cli.AppInstall.doCall(App.java:88)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at dev.jbang.util.Util.handleRedirects(Util.java:1084)
	at dev.jbang.util.Util.access$400(Util.java:75)
	at dev.jbang.util.Util$ResultHandler.lambda$redirects$0(Util.java:892)
	at dev.jbang.util.Util.connect(Util.java:814)
	at dev.jbang.util.Util.downloadFileAndCache(Util.java:743)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:694)
	at dev.jbang.source.resolvers.RemoteResourceResolver.fetchFromURL(RemoteResourceResolver.java:115)
	... 37 more

**Comment by maxandersen** [comment]
Are you behind a proxy by Any chance?

**Comment by cyongk** [comment]
thank you，Actually intercepted

**Comment by OMGgogong** [comment]
How to solve it？ @cyongk

**Comment by maxandersen** [comment]
https://www.jbang.dev/documentation/guide/latest/configuration.html#proxy-configuration

**Comment by quintesse** [comment]
@maxandersen shall we close this?
