### ISSUE TITLE
Error with JBang in GitLab pipelines: "no main class deduced, specified nor found in a manifest"

### ISSUE THREAD

**Issue by FDelporte** [jbangdev/jbang#1741]
**Describe the bug**
I use a JBang project to run several website and documentation quality tests with several JBang applications. From time to time one or more of these scripts with the following type of error:

```
[jbang] [0:951] jbang version 0.114.0
[jbang] [1:006] Resolving resource ref: tools/CheckHtmlLinks.java
[jbang] [1:021] Resolved resource ref as: tools/CheckHtmlLinks.java (cached as: /export/home/gitlab-runner/gitlab-runner/builds/BZpXtas4/0/docs/docs-quality-control/tools/CheckHtmlLinks.java)
[jbang] [1:325] Resolving artifact(s): org.jsoup:jsoup:1.15.3, com.fasterxml.jackson.core:jackson-core:2.12.3, com.fasterxml.jackson.core:jackson-databind:2.12.3, com.fasterxml.jackson.core:jackson-annotations:2.12.3
[jbang] [1:330] Repositories: central=https://repo1.maven.org/maven2/
[jbang] [1:568] Resolved artifact(s) from cache: org.jsoup:jsoup:jar:1.15.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/org/jsoup/jsoup/1.15.3/jsoup-1.15.3.jar, com.fasterxml.jackson.core:jackson-core:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar, com.fasterxml.jackson.core:jackson-databind:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar, com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar
[jbang] [1:582] Looking for JDK: 0
[jbang] [1:605] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:609] No build required. Reusing jar from /export/home/gitlab-runner/gitlab-runner/.jbang/cache/jars/CheckHtmlLinks.java.0409931e6e16e4eb9174f878fafe14efd8aa29b2c6522ce8496a014359f04700/CheckHtmlLinks.jar
[jbang] [1:621] Looking for JDK: 0
[jbang] [1:627] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:628] Looking for JDK: 0
[jbang] [1:629] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:632] [ERROR] no main class deduced, specified nor found in a manifest
dev.jbang.cli.ExitException: no main class deduced, specified nor found in a manifest
	at dev.jbang.source.generators.JarCmdGenerator.generateCommandLineList(JarCmdGenerator.java:177)
	at dev.jbang.source.generators.BaseCmdGenerator.generate(BaseCmdGenerator.java:54)
	at dev.jbang.cli.Run.doCall(Run.java:93)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)`
```

**To Reproduce**
* GitLab pipeline
* The same JBang script in several pipeline steps, with different parameters (args)

**Expected behavior**
All scripts get executed correctly.

**JBang version**
The latest, JBang is installed as the first step in the pipeline with SDKMAN.

**Additional context**

**Comment by FDelporte** [comment]
Locally = one by one = no problems
I guess my problem is that some pipeline steps run at the same time, maybe overwriting some other generated artifacts?

Maybe I'm "mis-using" JBang for this specific use-case...

**Comment by quintesse** [comment]
> maybe overwriting some other generated artifacts?

Perhaps, but I would expect different kinds of errors in that case.

Still, it's very hard to come up with a solution without knowing more about the particulars of your setup.
At the very least we'd need to be able to reproduce the problem ourselves.

**Comment by FDelporte** [comment]
You're right, I'll try reworking my project to full Maven, this just got a bit too big. JBang was perfect to get it started, but it grew a bit too fast ;-)

**Comment by maxandersen** [comment]
@FDelporte in theory there should not be a project too big for jbang :) I would like to grok why you are seeing this kind of failure. Basically its looking like your project has no main method in the classes compiled...if you have that when you do it locally it would be really interesting to grok why it fails in gitlab...if you can run with `--verbose` we will get more information on what its trying to do (and failing on)

**Comment by FDelporte** [comment]
Hi @maxandersen, with verbose not much more info is provided I'm afraid...

```
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
$ sdk install jbang
jbang 0.114.0 is already installed.
$ jbang --verbose tools/CheckHtmlLinks.java 
[jbang] [0:770] jbang version 0.114.0
[jbang] [0:840] Resolving resource ref: tools/CheckHtmlLinks.java
[jbang] [0:864] Resolved resource ref as: tools/CheckHtmlLinks.java (cached as: /export/home/gitlab-runner/gitlab-runner/builds/BZpXtas4/0/docs/docs-quality-control/tools/CheckHtmlLinks.java)
[jbang] [1:165] Resolving artifact(s): org.jsoup:jsoup:1.15.3, com.fasterxml.jackson.core:jackson-core:2.12.3, com.fasterxml.jackson.core:jackson-databind:2.12.3, com.fasterxml.jackson.core:jackson-annotations:2.12.3
[jbang] [1:177] Repositories: central=https://repo1.maven.org/maven2/
[jbang] [1:359] Resolved artifact(s) from cache: org.jsoup:jsoup:jar:1.15.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/org/jsoup/jsoup/1.15.3/jsoup-1.15.3.jar, com.fasterxml.jackson.core:jackson-core:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar, com.fasterxml.jackson.core:jackson-databind:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar, com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3=/export/home/gitlab-runner/gitlab-runner/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar
[jbang] [1:359] Looking for JDK: 0
[jbang] [1:384] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:385] No build required. Reusing jar from /export/home/gitlab-runner/gitlab-runner/.jbang/cache/jars/CheckHtmlLinks.java.0409931e6e16e4eb9174f878fafe14efd8aa29b2c6522ce8496a014359f04700/CheckHtmlLinks.jar
[jbang] [1:393] Looking for JDK: 0
[jbang] [1:393] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:394] Looking for JDK: 0
[jbang] [1:394] Using JDK: 19 (19, current, /export/home/gitlab-runner/gitlab-runner/.sdkman/candidates/java/19-zulu)
[jbang] [1:396] [ERROR] no main class deduced, specified nor found in a manifest
dev.jbang.cli.ExitException: no main class deduced, specified nor found in a manifest
	at dev.jbang.source.generators.JarCmdGenerator.generateCommandLineList(JarCmdGenerator.java:177)
	at dev.jbang.source.generators.BaseCmdGenerator.generate(BaseCmdGenerator.java:54)
	at dev.jbang.cli.Run.doCall(Run.java:93)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:145)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:148)
	at dev.jbang.cli.JBang$3.handle(JBang.java:143)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] [1:397] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
Cleaning up file based variables
```

**Comment by quintesse** [comment]
And what happens if you specify the main class manually (by using the `-m` option, eg: `jbang -m CheckClassName tools/CheckHtmlLinks.java`)

**Comment by FDelporte** [comment]
Still similar error

```
Error: Could not find or load main class tools.CheckHtmlLinks
Caused by: java.lang.ClassNotFoundException: tools.CheckHtmlLinks
```

But in the meantime, I found out, running the same jar simultaneously in different pipeline steps, also leads to errors. So I will need to rething my approach. The problem is not in JBang itself probably, but how GitLab executes Java?

**Comment by maxandersen** [comment]
Can you share the script? Or at least how your main is defined.

**Comment by FDelporte** [comment]
Very basic functionality...

But after more tests on my side, it's clear that running the same jar multiple times simultaneously, being with JBang or executed with java, causes problems on the GitLab runner. So I don't think this is a problem that can be fixed in JBang.

```
public class CheckRequiredFiles {

    private static String csv = """
            https://abc.de/assets/css/style.css
            https://abc.de/assets/img/logo.png
            https://abc.de/assets/js/scripts.js
            """;

    private static final TestResult testResult = new TestResult("Required files (js, css, images)");

    public static void main(String[] args) {
        try {
            List<String> requiredFiles = Arrays.asList(csv.split("\n"));
            System.out.println("Files to be checked: " + requiredFiles.size());
            requiredFiles.stream().forEach(s -> checkIfLinkIsValid(s));
        } catch (Exception e) {
            System.err.println("Error during check: " + e.getMessage());
            System.exit(911);
        }
    }

   ...
}
```

**Comment by maxandersen** [comment]
But jbang is just scanning the generated jar for a main method ...and somehow not finding it. Weird why gitlab runner should be able to make that not work.
