### ISSUE TITLE
windows 10 jdk install fails

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#188]
running on windows 10:

```
Z:\code\personal\jbang>build\install\jbang\bin\jbang hello.java
Downloading JDK 8...
Installing JDK 8...
java.lang.IllegalArgumentException
        at java.base/sun.nio.fs.WindowsPath.subpath(WindowsPath.java:689)
        at java.base/sun.nio.fs.WindowsPath.subpath(WindowsPath.java:42)
        at dev.jbang.UnpackUtil.unzip(UnpackUtil.java:43)
        at dev.jbang.UnpackUtil.unpack(UnpackUtil.java:27)
        at dev.jbang.JdkManager.downloadAndInstallJdk(JdkManager.java:40)
        at dev.jbang.JdkManager.getInstalledJdk(JdkManager.java:28)
        at dev.jbang.JdkManager.getCurrentJdk(JdkManager.java:21)
        at dev.jbang.cli.Run.resolveInJavaHome(Run.java:420)
        at dev.jbang.cli.Run.build(Run.java:152)
        at dev.jbang.cli.Run.doCall(Run.java:84)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:47)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:13)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at dev.jbang.Main.main(Main.java:14)

```

probably some path generation not honoring system path seperator.

**Comment by maxandersen** [comment]
whats even weirder is that consequtive run just runs on java 11 and ignoring //JAVA 8 ....

**Comment by maxandersen** [comment]
fixed
