### ISSUE TITLE
[ERROR] Couldn't find JBang wrapper files

### ISSUE THREAD

**Issue by vorburger** [jbangdev/jbang#1890]
**Describe the bug**

Background: I'm (re-, Hi 👋🏽 ) trying to use JBang in the context of https://github.com/enola-dev/enola/issues/971:

Based on https://www.jbang.dev/documentation/guide/latest/installation.html#wrapper-install, I assumed this was going to work (on a Fedora 41 Workstation):

**To Reproduce**
1. `sudo dnf copr enable @jbangdev/jbang && sudo dnf install jbang`
2. `jbang wrapper install --verbose`

**Expected behavior**

Have a `./jbang`... ?

**Actual behavior**

```
$ jbang wrapper install --verbose
[jbang] [0:255] jbang version 0.116.0
[jbang] [0:266] [ERROR] Couldn't find JBang wrapper files
dev.jbang.cli.ExitException: Couldn't find JBang wrapper files
        at dev.jbang.cli.Wrapper.install(Wrapper.java:51)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at dev.jbang.cli.JBang$3.handle(JBang.java:148)
        at dev.jbang.cli.JBang$3.handle(JBang.java:143)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] [0:267] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

**JBang version**
> Paste output of `jbang version --verbose`

```
[jbang] [0:266] jbang version 0.116.0
Cache: /home/vorburger/.jbang/cache
Config: /home/vorburger/.jbang
Repository: /home/vorburger/.m2/repository
0.116.0
```

**Additional context**

I will check if a more recent (latest v0.122.0 today) from https://github.com/jbangdev/jbang/releases/ perhaps has this fixed.

**Comment by vorburger** [comment]
> I will check if a more recent (latest v0.122.0 today) from https://github.com/jbangdev/jbang/releases/ perhaps has this fixed.

It works with v0.122.0:

```
[jbang] [0:257] jbang version 0.122.0
Cache: /home/vorburger/.jbang/cache
Config: /home/vorburger/.jbang
Repository: /home/vorburger/.m2/repository
Java: /usr/lib/jvm/java-21-openjdk-21.0.5.0.11-1.fc41.x86_64 [21.0.5]
OS: linux
Arch: x64
Shell: bash
0.122.0
```

I'm therefore going to close this.
