### ISSUE TITLE
Compilation fails with multiple sources feature when run from relative folder

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#325]
$ cat Sources/GitHub/service/src/main/java/Service.java
//DEPS info.picocli:picocli:4.5.0
//SOURCES ./Start.java
//SOURCES ./Stop.java
import picocli.CommandLine;
import picocli.CommandLine.Command;
import java.util.concurrent.Callable;

@Command(name = "service", subcommands = { Start.class, Stop.class })
public class Service implements Callable<Integer>
{
    @Override
    public Integer call() throws Exception
    {
        return null;
    }

    public static void main(String... args)
    {
        CommandLine commandLine = new CommandLine(new Service());
        commandLine.execute(args);
    }
}

$ jbang --verbose Sources/GitHub/service/src/main/java/Service.java stop -f myservice
[jbang] System Java version detected as 8
[jbang] System Java version matches requested version 8
[jbang] Building jar...
[jbang] compile: /home/pyfourmond/.jenv/versions/1.8/bin/javac -classpath /home/pyfourmond/.m2/repository/info/picocli/picocli/4.5.0/picocli-4.5.0.jar -d /home/pyfourmond/.jbang/cache/jars/Service.java.840fdfbb1fd8e99cee3a0084a28380a823bb50dcdac94d21c584d40d8d166ff2 Sources/GitHub/service/src/main/java/Service.java ./Start.java ./Stop.java
javac: file not found: ./Start.java
Usage: javac <options> <source files>
use -help for a list of possible options
dev.jbang.ExitException: Error during compile
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:140)
	at dev.jbang.cli.Run.doCall(Run.java:47)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:67)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:13)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)

**Comment by maxandersen** [comment]
reproduced and shuold be simple fix.

btw. `./Simple.java` will work but `Simple.java` should just work.

**Comment by maxandersen** [comment]
okey, this a simple fix. going to release 0.46.1 with it in.

**Comment by maxandersen** [comment]
@all-contributors please add @grumpyf0x48  for bug

**Comment by maxandersen** [comment]
fixed in 0.46.1 https://github.com/jbangdev/jbang/releases/tag/v0.46.1
