### ISSUE TITLE
Dependent files in multiple sources are not downloaded

### ISSUE THREAD

**Issue by grumpyf0x48** [jbangdev/jbang#328]
```console
$ jbang --verbose https://github.com/grumpyf0x48/service/blob/jbang/src/main/java/Service.java
[jbang] System Java version detected as 8
[jbang] System Java version matches requested version 8
[jbang] Building jar...
[jbang] compile: /home/pyfourmond/.jenv/versions/1.8/bin/javac -classpath /home/pyfourmond/.m2/repository/info/picocli/picocli/4.5.0/picocli-4.5.0.jar -d /home/pyfourmond/.jbang/cache/jars/Service.java.ff8a44aca681eb7a373c1e636675e9fc7a04263b5a5c18ec0454e7240ab257af /home/pyfourmond/.jbang/cache/urls/af80396bb1856c5d57ac7891907035efb6c1115cf47e3bfa3a70d0e2787a5349/Service.java /home/pyfourmond/.jbang/cache/urls/af80396bb1856c5d57ac7891907035efb6c1115cf47e3bfa3a70d0e2787a5349/Start.java /home/pyfourmond/.jbang/cache/urls/af80396bb1856c5d57ac7891907035efb6c1115cf47e3bfa3a70d0e2787a5349/Stop.java
javac: file not found: /home/pyfourmond/.jbang/cache/urls/af80396bb1856c5d57ac7891907035efb6c1115cf47e3bfa3a70d0e2787a5349/Start.java
Usage: javac <options> <source files>
use -help for a list of possible options
dev.jbang.ExitException: Error during compile
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:145)
	at dev.jbang.cli.Run.doCall(Run.java:47)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:67)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:13)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)

$ ls /home/pyfourmond/.jbang/cache/urls/af80396bb1856c5d57ac7891907035efb6c1115cf47e3bfa3a70d0e2787a5349/Service.java
```

**Comment by maxandersen** [comment]
In progress. Might have it before Monday :)
