### ISSUE TITLE
Add support for private catalogs

### ISSUE THREAD

**Issue by siancu** [jbangdev/jbang#338]
At work we have a self-hosted bitbucket instance. I've created a jbang-catalog repo with the corresponding jbang-catalog.json file, but when I want to add the catalog, it fails because of authentication issues.

It would be nice to be able to add such a private catalog to jbang.

**Comment by maxandersen** [comment]
So...pick up Host_TOKEN from env to use when fetching?

Or is there some convention we can use/rely on ?

**Comment by siancu** [comment]
That is a good question, I don't know to be honest. 

For bitbucket in particular, I found the following:

By default for authenticating against private Git repositories Bitbucket supports SSH and username/password Basic Auth over HTTPS. Username/password Basic Auth over HTTPS is also available for REST API access. Additionally Bitbucket supports App-specific passwords which can be used via Basic Auth as username/app-specific-password.

So I suppose user/pass Basic Auth could be used over https. Maybe add an option for the user to specify the user/pass?

**Comment by maxandersen** [comment]
Could you check if if you specify https with username/password fully if it just works ?

**Comment by siancu** [comment]
I just checked and it doesn't work. I get the following:

[jbang] dev.jbang.ExitException: Unable to download catalog: <url_of_catalog_here>

The command I used was this

`jbang catalog add cat https://user:pass@url.of.bitbucket.com/projects/PL/repos/jbang-catalog/raw/jbang-catalog.json`

If I then look at the downloaded .json file in ~/.jbang/cache/urls/... it's actually the login page of bitbucket. So it seems it's redirected to the login page.

**Comment by maxandersen** [comment]
So I do t have access to bitbucket to try but https://bitbucket.org/novocien/howto/src/master/ hints it should be doable as long as you use the right paths. Can you try that ?

**Comment by scambon** [comment]
I think that there is a larger problem with authenticated accesses.

Here is a scenario about running a GitHub-hosted script in a private repository:
1. Create a private repository in GitHub, e.g. `$USER/$REPO`
2. Create a script, e.g. `test.java`
3. Generate a Personal Access Token, e.g. `$PAT`
4. Add the script to the trusted sources: `jbang trust add https://$USER:$PAT@github.com` (`https://github.com` is not sufficient, running the script complains in that case)
5. Run the script `jbang --verbose https://$USER:$PAT@github.com/$USER/$REPO/blob/main/test.java`
```
[jbang] [ERROR] Could not download https://$USER:$PAT@github.com/$USER/$REPO/blob/main/test.java
dev.jbang.ExitException: Could not download https://$USER:$PAT@github.com/$USER/$REPO/blob/main/test.java
        at dev.jbang.cli.BaseScriptCommand.fetchFromURL(BaseScriptCommand.java:357)
        at dev.jbang.cli.BaseScriptCommand.getScriptFile(BaseScriptCommand.java:273)
        at dev.jbang.cli.BaseScriptCommand.prepareScript(BaseScriptCommand.java:113)
        at dev.jbang.cli.Run.doCall(Run.java:53)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download. Server replied HTTP code: 404
        at dev.jbang.Util.downloadFile(Util.java:458)
        at dev.jbang.Util.downloadFileSwizzled(Util.java:327)
        at dev.jbang.cli.BaseScriptCommand.fetchFromURL(BaseScriptCommand.java:353)
        ... 13 more
```
-> The URL is not translated to `https://$USER:$PAT@raw.githubusercontent.com/$USER/$REPO/main/test.java`
-> Postman properly loads the file from `https://$USER:$PAT@raw.githubusercontent.com/$USER/$REPO/main/test.java` (modern browsers do not like providing credentials using the `https://$USER:$PASSWORD@some.example.com` syntax)
-> It feels weird to mix credentials and trusted sources

**Comment by maxandersen** [comment]
Ah, yeah - we shouldn't include the auth part in trusted source calculation. Good catch!

**Comment by elgreco247** [comment]
What if you could specify an env variable holding additional headers for repository requests when adding a trusted domain?

For instance:
```
$> export EXAMPLE_HEADER="PRIVATE_TOKEN: 12345"
$> j! trust add --headerEnvVar=EXAMPLE_HEADER https://gitlab.example.com
```

All subsequent remote calls would have to lookup the trusted domain list first and query the specified env variable.

What do you think?

**Comment by maxandersen** [comment]
we have that for github (done in https://github.com/jbangdev/jbang/pull/590) - we can do similar for other services.

PRs very welcome.
