### ISSUE TITLE
Jbang 0.50.0 hangs when edit --live --open is used

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang#407]
```
~/workspace/quarkiverse/jbang-catalog (master ✘)✭ ᐅ jbang edit --live --open=idea updatecatalog.java
[jbang] Running `sh -i -c idea /home/ggastald/.jbang/cache/projects/updatecatalog.java_jbang_45ac532f09b7c638f171c762ead860b7d1933b7eaaeb4883d89306c1e4614fde/updatecatalog`
[jbang] Watching for changes in /home/ggastald/workspace/quarkiverse/jbang-catalog
^C^C^C^C^C
```

**Comment by maxandersen** [comment]
i can't reproduce.

what shell/os?

**Comment by gastaldi** [comment]
Fedora 32. I am using IntelliJ 2020.2.3 if that helps?

**Comment by gastaldi** [comment]
Here is the jstack output after I press Ctrl+C:

```bash
2020-10-08 17:49:11
Full thread dump OpenJDK 64-Bit Server VM (11.0.8+10 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007f26a40012e0, length=11, elements={
0x00007f2724016000, 0x00007f2724252800, 0x00007f2724256800, 0x00007f272426b800,
0x00007f272426d800, 0x00007f272426f800, 0x00007f2724271800, 0x00007f27242fe800,
0x00007f2724312000, 0x00007f27245b8000, 0x00007f26c0001000
}

"main" #1 prio=5 os_prio=0 cpu=473.53ms elapsed=221.07s tid=0x00007f2724016000 nid=0x1568e waiting on condition  [0x00007f2729667000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.8/Native Method)
	- parking to wait for  <0x00000006317190e0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.8/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.8/AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(java.base@11.0.8/LinkedBlockingDeque.java:483)
	at java.util.concurrent.LinkedBlockingDeque.take(java.base@11.0.8/LinkedBlockingDeque.java:671)
	at sun.nio.fs.AbstractWatchService.take(java.base@11.0.8/AbstractWatchService.java:118)
	at dev.jbang.cli.Edit.doCall(Edit.java:95)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=0.24ms elapsed=221.05s tid=0x00007f2724252800 nid=0x15695 waiting on condition  [0x00007f26f464b000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.8/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.8/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.8/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=0.39ms elapsed=221.05s tid=0x00007f2724256800 nid=0x15696 in Object.wait()  [0x00007f26f454a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.8/Native Method)
	- waiting on <0x0000000632a08f98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.8/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000632a08f98> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.8/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.8/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.28ms elapsed=221.04s tid=0x00007f272426b800 nid=0x15697 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=202.20ms elapsed=221.04s tid=0x00007f272426d800 nid=0x15698 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=266.05ms elapsed=221.04s tid=0x00007f272426f800 nid=0x15699 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=7.11ms elapsed=221.04s tid=0x00007f2724271800 nid=0x1569a runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #10 daemon prio=9 os_prio=0 cpu=0.21ms elapsed=221.02s tid=0x00007f27242fe800 nid=0x1569b runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=0 cpu=0.38ms elapsed=221.01s tid=0x00007f2724312000 nid=0x1569d in Object.wait()  [0x00007f26eddfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.8/Native Method)
	- waiting on <0x0000000632b88590> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.8/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000632b88590> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.8/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.8/InnocuousThread.java:134)

"FileSystemWatchService" #14 daemon prio=5 os_prio=0 cpu=0.62ms elapsed=220.59s tid=0x00007f27245b8000 nid=0x156ad runnable  [0x00007f26ed1cf000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.LinuxWatchService.poll(java.base@11.0.8/Native Method)
	at sun.nio.fs.LinuxWatchService$Poller.run(java.base@11.0.8/LinuxWatchService.java:316)
	at java.lang.Thread.run(java.base@11.0.8/Thread.java:834)

"Attach Listener" #15 daemon prio=9 os_prio=0 cpu=1.18ms elapsed=157.12s tid=0x00007f26c0001000 nid=0x15897 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=29.82ms elapsed=221.05s tid=0x00007f272424a800 nid=0x15694 runnable  

"GC Thread#0" os_prio=0 cpu=21.70ms elapsed=221.07s tid=0x00007f272402e000 nid=0x1568f runnable  

"G1 Main Marker" os_prio=0 cpu=0.35ms elapsed=221.07s tid=0x00007f2724067000 nid=0x15690 runnable  

"G1 Conc#0" os_prio=0 cpu=0.16ms elapsed=221.07s tid=0x00007f2724069000 nid=0x15691 runnable  

"G1 Refine#0" os_prio=0 cpu=0.38ms elapsed=221.06s tid=0x00007f27241e5000 nid=0x15692 runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=24.63ms elapsed=221.06s tid=0x00007f27241e6800 nid=0x15693 runnable  
"VM Periodic Task Thread" os_prio=0 cpu=102.26ms elapsed=221.01s tid=0x00007f2724301000 nid=0x1569c waiting on condition  

JNI global refs: 9, weak refs: 0
```

**Comment by gastaldi** [comment]
FYI it works with JBang 0.47.0. This is an issue in 0.50.0 only

**Comment by gastaldi** [comment]
100% confirmed it's a bug introduced in 0.48.0. It works on 0.47.1

**Comment by maxandersen** [comment]
the different from 0.47.1 to 0.48.0 is that jbang now launches the editor command using `sh` command to let you use aliases on linux (or on windows via cmd to let you use just `code` instead of `code.cmd`)

on windows and osx that seem to just work fine.

surprised fedora for some reason won't let ctrl+c get signaled in this case ;/

**Comment by maxandersen** [comment]
what happens if you do `jbang --live updatecatalog.java` (no --edit) ?

**Comment by gastaldi** [comment]
```bash
~/workspace/quarkiverse/jbang-catalog (master ✘)✭ ᐅ jbang --live updatecatalog.java 
Unknown option: '--live'
Usage: jbang run [-hno] [--[no-]cds] [--insecure] [--interactive] --quiet
                 --verbose [-r[=<flightRecorderString>]] [-d=<debugString>]
                 [-j=<javaVersion>] [-m=<main>] [--cp=<classpaths>]...
                 [-D=<String=String>]... [--deps=<dependencies>]...
                 [--javaagent=<String=String>]... <scriptOrFile>
                 [<userParams>...]
Builds and runs provided script.
      <scriptOrFile>         A file with java code or if named .jsh will be run
                               with jshell
      [<userParams>...]      Parameters to pass on to the script
      --[no-]cds             If specified Class Data Sharing (CDS) will be used
                               for building and running (requires Java 13+)
      --cp, --class-path=<classpaths>
                             Add class path entries.
  -d, --debug=<debugString>  Launch with java debug enabled on specified port
                               (default: 4004)
  -D=<String=String>         set a system property
      --deps=<dependencies>  Add additional dependencies.
  -h, --help                 Display help/info
      --insecure             Enable insecure trust of all SSL certificates.
      --interactive          activate interactive mode
  -j, --java=<javaVersion>   JDK version to use for running the script.
      --javaagent=<String=String>

  -m, --main=<main>          Main class to use when running. Used primarily for
                               running jar's.
  -n, --native               Build using native-image
  -o, --offline              Work offline. Fail-fast if dependencies are
                               missing.
      --quiet                jbang will be quiet, only print when error occurs.
  -r, --jfr[=<flightRecorderString>]
                             Launch with Java Flight Recorder enabled.
      --verbose              jbang will be verbose on what it does.

```

**Comment by gastaldi** [comment]
This doesn't: 
```bash
~/workspace/quarkiverse/jbang-catalog (master ✘)✭ ᐅ jbang edit --live --open=idea updatecatalog.java
[jbang] Running `sh -i -c idea /home/ggastald/.jbang/cache/projects/updatecatalog.java_jbang_45ac532f09b7c638f171c762ead860b7d1933b7eaaeb4883d89306c1e4614fde/updatecatalog`
[jbang] Watching for changes in /home/ggastald/workspace/quarkiverse/jbang-catalog
^C^C^C^C
```

**Comment by gastaldi** [comment]
Found the bug. Removing `-i` from
https://github.com/jbangdev/jbang/blob/master/src/main/java/dev/jbang/cli/Edit.java#L74 makes it work again.

**Comment by gastaldi** [comment]
@quintesse you have Fedora right? Can you check this bug happens to you as well? 0.51.0 didn't fix it for me and I am surprised people haven't hit into this bug yet

**Comment by maxandersen** [comment]
so i can confirm it stalls in a fedora docker container - no idea why though.

**Comment by maxandersen** [comment]
btw. gotta put this here and say its super awesome we can now just run/install java on *any* OS :)

```
docker run -it fedora
[root@5d45ca3f54f1 /]# curl
curl: try 'curl --help' or 'curl --manual' for more information
[root@5d45ca3f54f1 /]# curl -Ls https://sh.jbang.dev | bash -s - init test.java
Downloading JBang...
Installing JBang...
Downloading JDK 11. Be patient, this can take several minutes...
Installing JDK 11...
[jbang] Default JDK set to 11
[jbang] File initialized. You can now run it with 'jbang test.java' or edit it using 'code `jbang edit test.java`'

[root@5d45ca3f54f1 /]# curl -Ls https://sh.jbang.dev | bash -s - test.java
[jbang] Building jar...
Hello World
[root@5d45ca3f54f1 /]# curl -Ls https://sh.jbang.dev | bash -s - edit --live --open=code test.java
[jbang] Running `sh -i -c code /root/.jbang/cache/projects/test.java_jbang_1c436cf2aeafce304213d9280b803b3c98a0735c58f82784f665f40fbb693be4/test`
[jbang] Watching for changes in /
^C^C^C^C^C
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C
^C^C^C
```

**Comment by quintesse** [comment]
Indeed, I can reproduce the bug when I upgrade to 0.51.0. I actually still had a 0.44.2 version installed on the system and that one doesn't have the problem. So it's something that was introduced between that version and latest.
