### ISSUE TITLE
Quarkus generated classes written in / - read-only file system issue

### ISSUE THREAD

**Issue by cescoffier** [jbangdev/jbang#429]
It might be a Quarkus integration issue.
During the postBuild phase, generated classes are attempted to be written in the root (`/`, which obviously is not allowed):

```
[jbang] [ERROR] Issue running postBuild()
dev.jbang.ExitException: Issue running postBuild()
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:130)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:177)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:79)
	at dev.jbang.cli.Run.doCall(Run.java:68)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.nio.file.FileSystemException: /KafkaFailFast_KafkaFailFast$MovieWriter_SmallRyeMessagingInvoker_generate_f0bd56bb79a2a65285c41d9dafbe43c1181f10b0.class: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:118)
	... 13 more
```

To reproducer, you can use: 
```java
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS io.quarkus:quarkus-smallrye-reactive-messaging-kafka:1.9.0.CR1
//DEPS org.testcontainers:kafka:1.15.0-rc2
//JAVAC_OPTIONS -parameters
//JAVA_OPTIONS -Djava.util.logging.manager=org.jboss.logmanager.LogManager

//Q:CONFIG mp.messaging.outgoing.movies-out.connector=smallrye-kafka
//Q:CONFIG mp.messaging.outgoing.movies-out.topic=movies
//Q:CONFIG mp.messaging.outgoing.movies-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.annotations.QuarkusMain;
import io.smallrye.mutiny.Multi;
import org.eclipse.microprofile.reactive.messaging.Outgoing;
import org.jboss.logging.Logger;
import org.testcontainers.containers.KafkaContainer;
import org.testcontainers.utility.DockerImageName;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class KafkaFailFast {

    static final Logger LOGGER = Logger.getLogger("Kafka-Fail-Fast");

    @QuarkusMain
    static class Main {

        public static void main(String... args) {
            LOGGER.info("Starting Kafka...");
            KafkaContainer kafka = new KafkaContainer(
                 DockerImageName.parse("confluentinc/cp-kafka:5.2.1")
            );
            kafka.start();
            LOGGER.infof("Kafka started: %s", kafka.getBootstrapServers());
            System.setProperty("kafka.bootstrap.servers", kafka.getBootstrapServers());
            Quarkus.run(args);
        }
    }

    @ApplicationScoped
    static public class MovieWriter {

        @Outgoing("movies-out")
        public Multi<String> generate() {
          return   Multi.createFrom().items(
                    "The Shawshank Redemption",
                    "The Godfather",
                    "The Godfather: Part II",
                    "The Dark Knight",
                    "12 Angry Men",
                    "Schindler's List",
                    "The Lord of the Rings: The Return of the King",
                    "Pulp Fiction",
                    "The Good, the Bad and the Ugly",
                    "The Lord of the Rings: The Fellowship of the Ring"
            );
        }

    }
}
```

**Comment by maxandersen** [comment]
That is a quarkus integration issue. It probably missing some property/build item.

**Comment by maxandersen** [comment]
hmm, on second look - this shouldn't be able to happen. investigating.

**Comment by maxandersen** [comment]
okey, so for some reason Quarkus have not set the parent properly for the generated class "KafkaFailFast_KafkaFailFast$MovieWriter_SmallRyeMessagingInvoker_generate_f0bd56bb79a2a65285c41d9dafbe43c1181f10b0.class" its just root...that is Quarkus being wrong/weird.

@stuartwdouglas any idea ? otherwise I'll hunt some more later.

**Comment by maxandersen** [comment]
probably can work around it by checking if parent is not the same as what we passed in I should error..or print warning and then make sure it ends up inside the jar folder.. Would work around this.

**Comment by cescoffier** [comment]
does not seem to happen if I put a package.

**Comment by maxandersen** [comment]
Yeah it's something In quarkus messing things up when empty package.

**Comment by maxandersen** [comment]
marking as closed as issue was/is quarks not dealing with default packages.
