### ISSUE TITLE
Latest dependency version support

### ISSUE THREAD

**Issue by galderz** [jbangdev/jbang#432]
As libraries release versions, and you want to keep a catalog of scripts, it'd be great to have a way to define that a dependency should use the latest released version.

The classic workaround is to have a script that goes and changes all versions when a new version is released, but can see that getting quite tedious for rapidly evolving libraries.

**Comment by maxandersen** [comment]
so..turns out LATEST as version seem to work. It apparently only was removed for plugin deps in maven 3.

Thus i.e.  `info.picocli:picocli:LATEST` just seem to  work - of course; don't over use it :)

**Comment by maxandersen** [comment]
to clarify, LATEST means latest including snapshots, RELEASE means latest non-snapshot according to https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency/1172805#1172805

couldn't find an official doc for it so consider this use at your own risk :)

**Comment by quintesse** [comment]
Wow, no idea this existed :-)

**Comment by galderz** [comment]
Does this really work? I was expecting this to resolve to the [latest qollider version available on maven central](https://search.maven.org/artifact/org.mendrugo.qollider/qollider/0.0.13/jar).

```
[jbang]     Resolving org.mendrugo.qollider:qollider:LATEST...[jbang] Deleting folder /home/g/.jbang/cache/jars/graal.java.4e570ca398deb75eee9bce3842a3917f9862fa91e71f3eb3cdfc3b1ef12b5024.jar.tmp
[jbang] [ERROR] Could not resolve dependency
dev.jbang.cli.ExitException: Could not resolve dependency
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:198)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:205)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:110)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:59)
	at dev.jbang.source.ScriptSource.resolveClassPath(ScriptSource.java:187)
	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:261)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:146)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:120)
	at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:82)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:87)
	at dev.jbang.cli.Run.doCall(Run.java:77)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at org.mendrugo.qollider:qollider:jar:LATEST, caused by: Failed to resolve version for org.mendrugo.qollider:qollider:jar:LATEST
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:191)
	... 28 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.mendrugo.qollider:qollider:jar:LATEST
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
	... 32 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.mendrugo.qollider:qollider:jar:LATEST
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309)
	... 34 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.mendrugo.qollider:qollider:jar:LATEST
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:218)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:541)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:524)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:412)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 35 more
Caused by: org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for org.mendrugo.qollider:qollider:jar:LATEST
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:204)
	... 42 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

**Comment by galderz** [comment]
That syntax looks [deprecated](https://www.baeldung.com/maven-dependency-latest-version#1-deprecated-syntax).

**Comment by galderz** [comment]
Ah. only deprecated for plugin versions but regular dependencies should work.
