### ISSUE TITLE
Jbang Quarkus Scheduler Read-only file system Exception

### ISSUE THREAD

**Issue by weolopez** [jbangdev/jbang#561]
See and Run GIST here:

jbang --verbose https://gist.githubusercontent.com/weolopez/d6a6729f5be5febbfea46ba4b6a1a7a4/raw/6de6955cf8ed0a6bc0a3c4710cbc0f0b47fa647d/Jbang_Quarkus_Scheduler.java

**Comment by quintesse** [comment]
This is what I get if I run that:

```
dev.jbang.ExitException: Issue running postBuild()
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:130)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:206)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:129)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:70)
	at dev.jbang.cli.Run.doCall(Run.java:59)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.nio.file.AccessDeniedException: /Jbang_Quarkus_Scheduler_ScheduledInvoker_scheduledLog_4592414c73f13a2e41bdf89dccc9abe064eef0d7.class
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:118)
	... 14 more
```

Is it the same for you or do you get something else?

If something else could you post your output?

**Comment by weolopez** [comment]
Similar, I'm running on a mac

dev.jbang.ExitException: Issue running postBuild()
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:130)
	at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:206)
	at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:129)
	at dev.jbang.cli.Run.prepareArtifacts(Run.java:70)
	at dev.jbang.cli.Run.doCall(Run.java:59)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.nio.file.FileSystemException: /Jbang_Quarkus_Scheduler_ScheduledInvoker_scheduledLog_4592414c73f13a2e41bdf89dccc9abe064eef0d7.class: Read-only file system
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
	at dev.jbang.IntegrationManager.runIntegration(IntegrationManager.java:118)
	... 14 more

**Comment by maxandersen** [comment]
Can you try comment out  package?

It looks like a bug in a quarkus extension not handling default package.

**Comment by maxandersen** [comment]
just confirmed it works with package. thus this is a quarkus bug.

**Comment by maxandersen** [comment]
opened https://github.com/quarkusio/quarkus/issues/13540 to track this.

**Comment by maxandersen** [comment]
actually we should add detection of writing outside the designated directory. reopening for that.
