### ISSUE TITLE
Bitbucket raw url not working

### ISSUE THREAD

**Issue by KMUS** [jbangdev/jbang#693]
We host our own Bitbucket server and when I try to execute jbang with the raw link to the file, I always get an error.  I am sorry but I can not give you a working link.

```
user@home:~$ jbang --verbose https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] Downloaded file https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Building jar...
[jbang] compile: /opt/java/sdk/graalvm/bin/javac -classpath /home/user/.m2/repository/eu/hansolo/tilesfx/11.30/tilesfx-11.30.jar:/home/user/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/home/user/.m2/repository/junit/junit/4.10/junit-4.10.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1-linux.jar -d /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java
/home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java:82: error: class jfxtiles is public, should be declared in a file named jfxtiles.java
public class jfxtiles extends Application {
       ^
Note: /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
[jbang] Deleting folder /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd
[jbang] [ERROR] Error during compile
dev.jbang.ExitException: Error during compile
        at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:210)
        at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:137)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:83)
        at dev.jbang.cli.Run.doCall(Run.java:71)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```
```
wget https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
jbang jfxtiles.java
```

no errors

`
jbang https://raw.githubusercontent.com/jbangdev/jbang-examples/master/examples/jfxtiles.java`

no errors

**Comment by maxandersen** [comment]
Can you reproduce using public bitbucket ?

**Comment by KMUS** [comment]
> 
> 
> Can you reproduce using public bitbucket ?

Nope this works.

`jbang https://bitbucket.org/KMUSTEST/test/raw/0fd8a5b2c2a558a71bd19aa7f960f7d93516be16/jfxtiles.java`

**Comment by quintesse** [comment]
I'm guessing this has something to do with our handling of `Content-Disposition` as explained here: https://stackoverflow.com/a/6745788/2889926

**Comment by quintesse** [comment]
Also see RFC-5987 https://tools.ietf.org/html/rfc5987#section-3.2.2

**Comment by quintesse** [comment]
And a possible Java implementation: https://stackoverflow.com/a/63735284/2889926 (stripped from Spring, so APL2).

**Comment by KMUS** [comment]
> 
> 
> I'm guessing this has something to do with our handling of `Content-Disposition` as explained here: https://stackoverflow.com/a/6745788/2889926

Thanks for the hint. You are right.

`wget -SO- https://bitbucket.foorbar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java`

The response has a _Content-Disposition_ header.

> Content-Disposition: inline; filename="jfxtiles.java"; filename*=UTF-8''jfxtiles.java

`wget -SO- https://bitbucket.org/KMUSTEST/test/raw/0fd8a5b2c2a558a71bd19aa7f960f7d93516be16/jfxtiles.java`

No _Content-Disposition_ header in response.

**Comment by quintesse** [comment]
Yeah, the current implementation in Jbang is only useful for the most simple of cases. There's some simple fixes that would make it work for ore cases, but I studied the code I linked and I think that for true support that won't have any corner cases that will break we do need to use that code or something similarly complex.

**Comment by quintesse** [comment]
Well, I created a PR with a simple implementation anyway. It's only a dozen lines or so and it's definitely not foolproof but it was easy enough to write and should handle most cases.

**Comment by KMUS** [comment]
Sorry but still not working.

```
user@home:~$ jbang -V
0.64.0
```

```
wget https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
jbang jfxtiles.java
```

This works.

```
user@home:~$ jbang --verbose https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] Downloaded file https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Building jar...
[jbang] compile: /opt/java/sdk/graalvm/bin/javac -classpath /home/user/.m2/repository/eu/hansolo/tilesfx/11.30/tilesfx-11.30.jar:/home/user/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/home/user/.m2/repository/junit/junit/4.10/junit-4.10.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1-linux.jar -d /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd.jar.tmp /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java
/home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java:82: error: class jfxtiles is public, should be declared in a file named jfxtiles.java
public class jfxtiles extends Application {
       ^
Note: /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
[jbang] Deleting folder /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd.jar.tmp
[jbang] [ERROR] Error during compile
dev.jbang.cli.ExitException: Error during compile
        at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:201)
        at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:130)
        at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:93)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:84)
        at dev.jbang.cli.Run.doCall(Run.java:74)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

**Comment by quintesse** [comment]
Hmmm, could you try running `jbang cache clear` and try again?

**Comment by KMUS** [comment]
> 
> 
> Hmmm, could you try running `jbang cache clear` and try again?

Sure but still the same problem.
```

user@home:~$ jbang cache clear
[jbang] Clearing cache for urls
[jbang] Clearing cache for jars
[jbang] Clearing cache for scripts
[jbang] Clearing cache for stdins
[jbang] Clearing cache for deps
user@home:~$ jbang --verbose https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] Downloaded file https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Resolving dependencies...
[jbang]     Resolving eu.hansolo:tilesfx:11.30...Done
[jbang] Dependencies resolved
[jbang] Building jar...
[jbang] compile: /opt/java/sdk/graalvm/bin/javac -classpath /home/user/.m2/repository/eu/hansolo/tilesfx/11.30/tilesfx-11.30.jar:/home/user/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar:/home/user/.m2/repository/junit/junit/4.10/junit-4.10.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-media/12.0.1/javafx-media-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-controls/12.0.1/javafx-controls-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-web/12.0.1/javafx-web-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-base/12.0.1/javafx-base-12.0.1-linux.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1.jar:/home/user/.m2/repository/org/openjfx/javafx-graphics/12.0.1/javafx-graphics-12.0.1-linux.jar -d /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd.jar.tmp /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java
/home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java:82: error: class jfxtiles is public, should be declared in a file named jfxtiles.java
public class jfxtiles extends Application {
       ^
Note: /home/user/.jbang/cache/urls/9d201cddd21d493a35432a75483dc1e1f3629a1eb18f3d536e7a09f30e7e8eaf/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
[jbang] Deleting folder /home/user/.jbang/cache/jars/"jfxtiles.java"; filename*=UTF-8''jfxtiles.java.a559f83ce53db9459dc66a853ea4d72d27050beb88a0d13ec0b70a84cd2ac5cd.jar.tmp
[jbang] [ERROR] Error during compile
dev.jbang.cli.ExitException: Error during compile
        at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:201)
        at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:130)
        at dev.jbang.cli.BaseBuildCommand.buildIfNeeded(BaseBuildCommand.java:93)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:84)
        at dev.jbang.cli.Run.doCall(Run.java:74)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

**Comment by KMUS** [comment]
Some more verbose output of the request.

```
user@home:~$ curl -v  https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
*   Trying 185.39.176.38:443...
* TCP_NODELAY set
* Connected to bitbucket.foobar.net (185.39.176.38) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; ST=Niedersachsen; L=Goslar; OU=Entwicklung; O=foobar AG; CN=*.foobar.net
*  start date: May 12 13:32:36 2020 GMT
*  expire date: Jul  9 23:59:59 2021 GMT
*  subjectAltName: host "bitbucket.foobar.net" matched cert's "*.foobar.net"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ce17578800)
> GET /projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java HTTP/2
> Host: bitbucket.foobar.net
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< server: nginx
< date: Fri, 05 Feb 2021 19:50:38 GMT
< content-type: text/plain;charset=UTF-8
< x-arequestid: @V0DICMx1190x680090x0
< x-asen: SEN-12179585
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< pragma: no-cache
< expires: Thu, 01 Jan 1970 00:00:00 GMT
< cache-control: no-cache
< cache-control: no-store
< content-disposition: inline; filename="jfxtiles.java"; filename*=UTF-8''jfxtiles.java
< vary: accept-encoding
<
//DEPS eu.hansolo:tilesfx:11.30
/*
```

**Comment by KMUS** [comment]
Some more verbose output of the request.

```
user@home:~$ curl -v  https://bitbucket.foobar.net/projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java
*   Trying x.x.x.x:443...
* TCP_NODELAY set
* Connected to bitbucket.foobar.net (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=xx; ST=xyz; L=xyz; OU=xyz; O=foobar; CN=*.foobar.net
*  start date: May 12 13:32:36 2020 GMT
*  expire date: Jul  9 23:59:59 2021 GMT
*  subjectAltName: host "bitbucket.foobar.net" matched cert's "*.foobar.net"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55ce17578800)
> GET /projects/JBAN/repos/examples/raw/src/main/java/examples/jfxtiles.java HTTP/2
> Host: bitbucket.foobar.net
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200
< server: nginx
< date: Fri, 05 Feb 2021 19:50:38 GMT
< content-type: text/plain;charset=UTF-8
< x-arequestid: @V0DICMx1190x680090x0
< x-asen: SEN-12179585
< x-xss-protection: 1; mode=block
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< pragma: no-cache
< expires: Thu, 01 Jan 1970 00:00:00 GMT
< cache-control: no-cache
< cache-control: no-store
< content-disposition: inline; filename="jfxtiles.java"; filename*=UTF-8''jfxtiles.java
< vary: accept-encoding
<
//DEPS eu.hansolo:tilesfx:11.30
/*
```

**Comment by quintesse** [comment]
Ha, didn't read the spec right: "When both filename and filename* are present in a single header field value, filename* is preferred over filename when both are understood."

**Comment by quintesse** [comment]
Ok, this should now be a better fix. It should at least handle your particular case @KMUS :-)

**Comment by quintesse** [comment]
@KMUS the latest version of jbang should fix your problem now. :crossed_fingers:

**Comment by KMUS** [comment]
> 
> 
> @KMUS the latest version of jbang should fix your problem now. 🤞

Thanks for fixing. It works perfectly now.
