### ISSUE TITLE
[enhancement] vscode: run quarkus scripts with Code Runner extension

### ISSUE THREAD

**Issue by lburgazzoli** [jbangdev/jbang#784]
I have the [Code Runner](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) extension installed on VS Code  which adds a nice and convenient `Run|Debug` button/menu 

![image](https://user-images.githubusercontent.com/1868933/111602769-fb5da680-87d3-11eb-91dd-cbbfc5f96327.png)

When using it with a quarkus based script, it leads to the following error:

```
Caused by: java.lang.RuntimeException: org.gradle.tooling.UnknownModelException: No model of type 'QuarkusModel' is available in this build.
        at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:80)
        ... 10 more
Caused by: org.gradle.tooling.UnknownModelException: No model of type 'QuarkusModel' is available in this build.
        at org.gradle.tooling.model.internal.Exceptions.unknownModel(Exceptions.java:57)
        at org.gradle.tooling.internal.consumer.connection.CancellableModelBuilderBackedModelProducer.produceModel(CancellableModelBuilderBackedModelProducer.java:56)
        at org.gradle.tooling.internal.consumer.connection.PluginClasspathInjectionSupportedCheckModelProducer.produceModel(PluginClasspathInjectionSupportedCheckModelProducer.java:38)
        at org.gradle.tooling.internal.consumer.connection.AbstractConsumerConnection.run(AbstractConsumerConnection.java:64)
        at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:49)
        at org.gradle.tooling.internal.consumer.DefaultModelBuilder$1.run(DefaultModelBuilder.java:64)
        at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:144)
        at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
        at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:61)
        at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
        at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:67)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
        at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:51)
        at io.quarkus.bootstrap.resolver.QuarkusGradleModelFactory.createForTasks(QuarkusGradleModelFactory.java:32)
        at io.quarkus.bootstrap.utils.BuildToolHelper.enableGradleAppModelForDevMode(BuildToolHelper.java:107)
        at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:38)
        ... 10 more
Caused by: org.gradle.tooling.provider.model.UnknownModelException: No builders are available to build a model of type 'io.quarkus.bootstrap.resolver.model.QuarkusModel
```

it would be very nice to get jbang script compatibles with "Code Run"

**Comment by maxandersen** [comment]
@fbricon what is this level of evil magic ? :)

why would 'quarkusmodel' show up here ?

**Comment by fbricon** [comment]
My guess is quarkus sees the build.gradle file generated by jbang, then it tries to build the quarkus model, but this is not a real quarkus build.gradle so it's lacking some proper config, then fails.

And I'm in no way involved in code-runner, which might as well be a part of the issue.

**Comment by maxandersen** [comment]
Ok... So I bug report it against vscode-quarkus?

**Comment by fbricon** [comment]
Probably not. First, you need to try with the vscode-java+vscode-java-debug. We do not support code-runner. I don't know what dark magic they use to build their classpath.
