### ISSUE TITLE
v0.69.1 breaks compatibility with JDK 8.

### ISSUE THREAD

**Issue by michael-simons** [jbangdev/jbang#806]
Given `demo.java`

```java
public class demo {
    public static void main(String...a) {
        System.out.println("Hallo");
    }
}
```

Running

```
docker run -v `pwd`:/ws --workdir=/ws jbangdev/jbang-action:0.69.1 --java 8 demo.java
```

fails with

```
jbang --java 8 demo.java
[jbang] Building jar...
[jbang] Downloading JDK 8. Be patient, this can take several minutes...
[jbang] Installing JDK 8...
[jbang] Default JDK set to 8
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: demo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

Where as `docker run -v `pwd`:/ws --workdir=/ws jbangdev/jbang-action:0.68.0 --java 8 demo.java` say

```
[jbang] Downloading JDK 8. Be patient, this can take several minutes...
[jbang] Installing JDK 8...
[jbang] Default JDK set to 8
[jbang] Building jar...
[jbang] There is a new version of jbang available!
[jbang] You have version 0.68.0 and 0.69.1 is the latest.
[jbang] Use your package manager to update jbang to the latest version,
[jbang] or visit https://jbang.dev to download and install it yourself.
Hallo
```

**Comment by maxandersen** [comment]
something is wrong with java version being passed around:

```
 jbang --fresh --verbose --java 8 test.java
[jbang] jbang version 0.69.0
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Building jar...
[jbang] compile: /Users/max/.sdkman/candidates/java/current/bin/javac -d /Users/max/.jbang/cache/jars/test.java.7acbfa8c1d192be90251dc1512ceaeeb0f2c51930dc52f36cde2c50807d557d3.jar.tmp /Users/max/code/work/quarkus/jbang-catalog/test.java
[jbang] Deleting folder /Users/max/.jbang/cache/jars/test.java.7acbfa8c1d192be90251dc1512ceaeeb0f2c51930dc52f36cde2c50807d557d3.jar.tmp
[jbang] System Java version 11 incompatible, using Jbang managed version 8
[jbang] run: /Users/max/.jbang/cache/jdks/8/bin/java -classpath /Users/max/.jbang/cache/jars/test.java.7acbfa8c1d192be90251dc1512ceaeeb0f2c51930dc52f36cde2c50807d557d3.jar test
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: test has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

see that it uses java 11 for compilation but java 8  for run

**Comment by maxandersen** [comment]
found it - version requested was not passed through properly - should noww be fixed

**Comment by maxandersen** [comment]
fix released - should hit the various places soon.
if you could verify with a comment on this issue that it is fixed for you that would be great @michael-simons 

@all-contributors please add @michael-simons  for bug

**Comment by michael-simons** [comment]
Will do! Thanks for the quick reaction!

**Comment by michael-simons** [comment]
Can confirm, works for all (action, docker image, standalone). Thanks again.

**Comment by maxandersen** [comment]
Thanks for reporting and confirming fix!
