### ISSUE TITLE
how to deal with uber jars with "bad" pom.xml

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#813]
if you run `jbang io.quarkus:quarkus-cli:1.13.0.Final:runner` you end up with duplicate classpath as the uber jar has everything but pom.xml still contains dependencies.

should jbang have an option to say dont resolve transitive depednencies ?

i.e. `jbang --no-transitive` or even just have `jbang --jar` that would use -jar for launch and then just ignore --class-path and skip resolve step?

**Comment by cmoulliard** [comment]
As this ticket is still open, that means (I suppose) that the problem is not yet fixed and reason why I cannot use a shaded jar when running jbang - correct ?

```
//DEPS dev.snowdrop.openrewrite:client:jar:shaded:0.3.2 => which is available here: https://repo.maven.apache.org/maven2/dev/snowdrop/openrewrite/service/0.3.2/

❯ jbang -x run ./src/main/java/dev/snowdrop/RewriteApp.java ../demo
[jbang] Resolving dependencies...
[jbang] [ERROR] Could not read artifact descriptor for dev.snowdrop.openrewrite:service:jar:shaded:0.3.2:jar
dev.jbang.cli.ExitException: Could not read artifact descriptor for dev.snowdrop.openrewrite:service:jar:shaded:0.3.2:jar
        at dev.jbang.dependencies.ArtifactResolver.resolveDescriptor(ArtifactResolver.java:379)
        at dev.jbang.dependencies.ArtifactResolver.getManagedDependencies(ArtifactResolver.java:348)
        at dev.jbang.dependencies.ArtifactResolver.lambda$resolve$1(ArtifactResolver.java:209)
        at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:288)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1716)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:723)
        at dev.jbang.dependencies.ArtifactResolver.resolve(ArtifactResolver.java:210)
        at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:118)
        at dev.jbang.dependencies.DependencyResolver.resolve(DependencyResolver.java:66)
        at dev.jbang.source.BuildContext.resolveClassPath(BuildContext.java:118)
        at dev.jbang.source.sources.JavaSource$JavaAppBuilder$JavaCompileBuildStep.getCompileCommandOptions(JavaSource.java:97)
        at dev.jbang.source.buildsteps.CompileBuildStep.getCompileCommand(CompileBuildStep.java:81)
        at dev.jbang.source.buildsteps.CompileBuildStep.compile(CompileBuildStep.java:58)
        at dev.jbang.source.buildsteps.CompileBuildStep.build(CompileBuildStep.java:54)
        at dev.jbang.source.buildsteps.CompileBuildStep.build(CompileBuildStep.java:39)
        at dev.jbang.source.AppBuilder.build(AppBuilder.java:97)
        at dev.jbang.source.AppBuilder.build(AppBuilder.java:22)
        at dev.jbang.cli.Run.doCall(Run.java:88)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:149)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:24)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2031)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2469)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2461)
        at dev.jbang.cli.JBang$3.handle(JBang.java:166)
        at dev.jbang.cli.JBang$3.handle(JBang.java:161)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2425)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at dev.jbang.Main.main(Main.java:28)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for dev.snowdrop.openrewrite:service:jar:shaded:0.3.2:jar
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:254)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:183)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:269)
        at dev.jbang.dependencies.ArtifactResolver.resolveDescriptor(ArtifactResolver.java:377)
        ... 33 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: dev.snowdrop.openrewrite:service:pom:jar (absent): Could not find artifact dev.snowdrop.openrewrite:service:pom:jar in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:473)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:243)
        ... 36 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact dev.snowdrop.openrewrite:service:pom:jar in central (https://repo1.maven.org/maven2/)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:42)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:417)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:260)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:537)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
        ... 39 more
```

**Comment by maxandersen** [comment]
No, the issue you see an error is that there is no client shaded jar, and that the format is wrong.
 
client is a runner and is at https://repo.maven.apache.org/maven2/dev/snowdrop/openrewrite/client/0.3.2/
and format would be:

`//DEPS dev.snowdrop.openrewrite:client:0.3.2:runner`

if it is the service jar (not client) then it is not a runner, but shaded:

`//DEPS dev.snowdrop.openrewrite:service:0.3.2:shaded`

**Comment by maxandersen** [comment]
solution to the specific original issue here is the @fatjar syntax handled in #1800

**Comment by cmoulliard** [comment]
> if it is the service jar (not client) then it is not a runner, but shaded:

I also discovered my typo error this morning. this is fixed now ;-). Thanks
