### ISSUE TITLE
j'bang should recompile class if script is rerun using a different JDK version

### ISSUE THREAD

**Issue by fbricon** [jbangdev/jbang#83]
I initially ran my jbang script with Java 11. Much later on, I had to switch the default Java version in my terminal, to Java 8. When rerunning, j'bang fails because it's trying to rerun the already compiled class:
```
❯ jbang https://gist.githubusercontent.com/fbricon/4028e0e2dda01acd0e7bd0f3e3c2ed63/raw/e06c5553387e5d357f9d38426a9c3c2289104425/GenerateChangelog.java https://github.com/redhat-developer/vscode-java/milestone/73 https://github.com/eclipse/eclipse.jdt.ls/milestone/72
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: GenerateChangelog has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

Hopefully I could fix it with `jbang --clear-cache`, but maybe the path of the cached class could be encoded with the JVM or java version used to compile it, to avoid that issue.

**Comment by maxandersen** [comment]
hmm - here I thought once you go java 11 you never go back ? :) 

not sure there is a reliable thing to key on here.....but yeah; would be nice to handle more cleanly.

**Comment by maxandersen** [comment]
just because java 11 was used to compile does not mean java 8 can't run it...

**Comment by fbricon** [comment]
You'd have to set the target compilation to 8 for it to work

**Comment by maxandersen** [comment]
yes, which you can :)

```//JAVAC_OPTIONS --target 8```

**Comment by fbricon** [comment]
Need to define source too apparently:

> //JAVAC_OPTIONS -source 1.8 -target 1.8

**Comment by quintesse** [comment]
Perhaps keying on the Java version wouldn't be that bad? It might be a little bit of a nuisance if you often switch between multiple Java versions, but I'm not sure if it's worth optimizing for situations like that. After all compilation is fairly quick and all Maven dependencies will already have been downloaded,

The Java version could be part of the cache key so you'd get a cached version for each file/java-version.

**Comment by quintesse** [comment]
Oh btw, nowadays I think it's better to use `--release` than `--source` and `--target` (because those don't handle the fact that without also setting the `-bootclasspath` you'd still be compiling against a newer JDK API)

**Comment by maxandersen** [comment]
to use `--release` would require we detect what vm we will be running on ...I guess we could...but how do you refer to the different jdk then ?

**Comment by maxandersen** [comment]
> Perhaps keying on the Java version wouldn't be that bad?

I guess keying on major version should be enough ?

**Comment by quintesse** [comment]
> I guess keying on major version should be enough ?

I think so yes. A better option might be the source version but there's no easy we to retrieve that. Although I did notice that if you ask `javac` for it's version number it's much more straightforward than the one from `java`. So perhaps less parsing to do.
