### ISSUE TITLE
download of jdk does not work on windows if on different filesystems

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#888]
I have a windows virtual machine where my home is on C:\ but my jbangdir is on Z:\ and things fails.

```
[jbang] [ERROR] Unable to download or install JDK version 11
dev.jbang.cli.ExitException: Unable to download or install JDK version 11
        at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:86)
        at dev.jbang.net.JdkManager.getInstalledJdk(JdkManager.java:46)
        at dev.jbang.net.JdkManager.getCurrentJdk(JdkManager.java:39)
        at dev.jbang.util.JavaUtil.resolveInJavaHome(JavaUtil.java:161)
        at dev.jbang.cli.Run.generateCommandLineList(Run.java:163)
        at dev.jbang.cli.Run.generateOSCommandLine(Run.java:112)
        at dev.jbang.cli.Run.doCall(Run.java:79)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
        at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at dev.jbang.Main.main(Main.java:14)
Caused by: dev.jbang.cli.ExitException: java.nio.file.FileSystemException: C:\Users\max\.jbang\currentjdk -> Z:\.jbangwin\jdks\11: The system cannot move the file to a different disk drive.

        at dev.jbang.util.Util.createHardLink(Util.java:953)
        at dev.jbang.util.Util.createLink(Util.java:930)
        at dev.jbang.net.JdkManager.setDefaultJdk(JdkManager.java:167)
        at dev.jbang.net.JdkManager.downloadAndInstallJdk(JdkManager.java:72)
        ... 17 more
Caused by: java.nio.file.FileSystemException: C:\Users\max\.jbang\currentjdk -> Z:\.jbangwin\jdks\11: The system cannot move the file to a different disk drive.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsFileSystemProvider.createLink(WindowsFileSystemProvider.java:608)
        at java.nio.file.Files.createLink(Files.java:1086)
        at dev.jbang.util.Util.createHardLink(Util.java:950)
        ... 20 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

**Comment by maxandersen** [comment]
I have this setup from `jbang version --verbose`

```
[jbang] jbang version 0.71.1
Cache: Z:\.jbangwin
Config: C:\Users\max\.jbang
Repository:C:\Users\max\.m2\repository
0.71.1
```

notice cache and config not in same place.

**Comment by quintesse** [comment]
> notice cache and config not in same place.

Is that because you have the JBANG_CACHE_DIR set, but not the JBANG_DIR?

**Comment by quintesse** [comment]
No exactly sure why it fails for you. It works for me here. Do you have rights to create links?

**Comment by maxandersen** [comment]
I'm not admin. So limited at times.

**Comment by quintesse** [comment]
This is what our docs say:

> On Windows you might need elevated privileges to create symbolic links. If you don’t have permissions then running the above command will result in an error. To use it [enable symbolic links](https://stackoverflow.com/a/24353758) for your user or run your shell/terminal as administrator to have this feature working.

**Comment by maxandersen** [comment]
But that's just for edit...didn't realize that applied for jdk instsll. 

But I guess I can see that be the case for current jdk link too. 

Gotcha.

**Comment by maxandersen** [comment]
closing as for now it is a limitation windows user will have to live with or not use jbangs jdk mangagement and config across filesystems.

**Comment by quintesse** [comment]
what limitation? There's no limitation really, it all works fine on my system. The only thing is that you need to give your user the rights to create symbolic links. Or am I missing something?

**Comment by maxandersen** [comment]
If you can find a way for that to happen across file systems let me know :)

**Comment by quintesse** [comment]
I told you, it works here :-)

**Comment by quintesse** [comment]
![image](https://user-images.githubusercontent.com/778793/119960024-d4c2a580-bfa4-11eb-835a-ce18cf2d04a1.png)

**Comment by maxandersen** [comment]
And you are not running as admin ?

Any idea what permission you granted ?

**Comment by quintesse** [comment]
I'm not running as admin and I just followed the instructions in the link above https://github.com/jbangdev/jbang/issues/888#issuecomment-849064113
