### ISSUE TITLE
Native Image doesn't work with tar.gz files on MacOS

### ISSUE THREAD

**Issue by will-sargent-eero** [jbangdev/jbang#948]
Native Image doesn't work with tar.gz files on MacOS and sdkman:

Set up graal with sdkman:

```
# Enable auto-env through the sdkman_auto_env config
# Add key=value pairs of SDKs to use below
java=21.1.0.r16-grl
```

Install sdk java with `sdk env install` / `sdk env`:

```java
//DEPS org.graalvm.nativeimage:svm:21.1.0

public class hello {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
```

And then install `native-image`:

```
 ✘ wsargen@38f9d32cde81  ~/jbang  gu install native-image
Downloading: Component catalog from www.graalvm.org
Processing Component: Native Image
Downloading: Component native-image: Native Image  from github.com
Installing new component: Native Image (org.graalvm.native-image, version 21.1.0)
 wsargen@38f9d32cde81  ~/jbang  jbang --native hello.java
[jbang] Building jar...
[jbang] log: /var/folders/md/x0cjwgz960dcfgx2ypz89070jqm1k7/T/jbang7803174174046555325native-image
Error: Unable to handle classpath element '/Users/wsargen/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-windows-amd64/21.1.0/svm-hosted-native-windows-amd64-21.1.0.tar.gz'. Make sure that all classpath entries are either directories or valid jar files.
com.oracle.svm.core.util.UserError$UserException: Unable to handle classpath element '/Users/wsargen/.m2/repository/org/graalvm/nativeimage/svm-hosted-native-windows-amd64/21.1.0/svm-hosted-native-windows-amd64-21.1.0.tar.gz'. Make sure that all classpath entries are either directories or valid jar files.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:175)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$14(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$2(NativeImageGenerator.java:495)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1414)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
[jbang] [ERROR] Error during native-image
[jbang] Run with --verbose for more details
```

**Comment by will-sargent-eero** [comment]
Possible dup of https://github.com/jbangdev/jbang/issues/598

**Comment by maxandersen** [comment]
Yeah it's graalvm not honoring the Java command line contract of ignoring anything not a jar on the classpath. 

What is the usecase you are trying to solve here by having that dependency on the classpath?

**Comment by will-sargent-eero** [comment]
I just want to have a native image that says "hello world."  I'm a simple programmer.

**Comment by will-sargent-eero** [comment]
This works, I want to verify that a native image is created that I can pass around though...

```
// curl -s "https://get.sdkman.io" | bash
// source "$HOME/.sdkman/bin/sdkman-init.sh"
// echo java=21.1.0.r16-grl > .sdkmanrc
// sdk env install
// sdk env
// gu install native-image
// jbang --native hello.java

public class hello {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
```

**Comment by maxandersen** [comment]
jbang export local --native app.java will do that for you (building if necessary)

**Comment by maxandersen** [comment]
And yeah would make sense we install graalvm if native requested.

**Comment by maxandersen** [comment]
I've added a line in the docs about jbang export with native image.

@all-contributors please add @will-sargent-eero  for bugs
