### ISSUE TITLE
jbang catalog list and jbang alias fails if  catalog is giving 404

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang#965]
```
jbang catalog list
[jbang] [ERROR] Could not download https://github.com/maxandersen/jbang/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details
```

```
[jbang] [ERROR] Could not download https://github.com/maxandersen/jbang/blob/HEAD/jbang-catalog.json
dev.jbang.cli.ExitException: Could not download https://github.com/maxandersen/jbang/blob/HEAD/jbang-catalog.json
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:321)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:229)
	at dev.jbang.source.ResourceRef.forResource(ResourceRef.java:151)
	at dev.jbang.catalog.Catalog.getByRef(Catalog.java:190)
	at dev.jbang.catalog.Catalog.merge(Catalog.java:248)
	at dev.jbang.catalog.Catalog.getMerged(Catalog.java:240)
	at dev.jbang.cli.AliasList.doCall(Alias.java:122)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: java.io.FileNotFoundException: No file to download. Server replied HTTP code: 404
	at dev.jbang.util.Util.downloadFile(Util.java:592)
	at dev.jbang.util.Util.downloadFile(Util.java:512)
	at dev.jbang.util.Util.downloadAndCacheFile(Util.java:664)
	at dev.jbang.source.ResourceRef.fetchFromURL(ResourceRef.java:318)
	... 17 more
```

i would say we should at most WARN - not fail hard here as it means you can't list aliases for even local files.

**Comment by maxandersen** [comment]
even worse it came from implicit catalog json which the user haven't even asked to get added :)

**Comment by maxandersen** [comment]
@quintesse thoughts? ^^
