### ISSUE TITLE
[jbang] [ERROR] Could not resolve dependency

### ISSUE THREAD

**Issue by tarilabs** [jbangdev/jbang#985]
Hi 
for some reason one specific dependency does not resolve in the jbang scripts:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
//DEPS org.kie:kie-dmn-xls2dmn-cli:RELEASE
```

with:

<details>
<summary>verbose</summary>

```bash
jbang-catalog $ jbang --verbose edit --open=code xls2dmn.java
[jbang] jbang version 0.78.0
[jbang] Resolving dependencies...
[jbang]     Resolving org.kie:kie-dmn-xls2dmn-cli:RELEASE...[jbang] [ERROR] Could not resolve dependency org.kie:kie-dmn-xls2dmn-cli:RELEASE
dev.jbang.cli.ExitException: Could not resolve dependency org.kie:kie-dmn-xls2dmn-cli:RELEASE
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:201)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:208)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:113)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:62)
	at dev.jbang.source.ScriptSource.resolveClassPath(ScriptSource.java:210)
	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:261)
	at dev.jbang.cli.Edit.createProjectForEdit(Edit.java:215)
	at dev.jbang.cli.Edit.doCall(Edit.java:70)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE, caused by: Failed to resolve version for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:194)
	... 25 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
	... 29 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309)
	... 31 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:218)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:541)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:524)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:412)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 32 more
Caused by: org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:204)
	... 39 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

</details>

While other works just fine, examples

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
//DEPS org.kie:kie-dmn-core:RELEASE
```

works fine; or:

```java
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 11+
//DEPS org.kie:kie-dmn-feel:RELEASE
```

works fine too.

Any idea what I'm doing wrong, please?
Thanks!

**Comment by quintesse** [comment]
Indeed, it surprises me it works at all, because according to this `RELEASE` and `LATEST` were deprecated and even removed from Maven: https://stackoverflow.com/questions/54344527/versionresolutionexception-failed-to-resolve-version-release

**Comment by tarilabs** [comment]
Thanks @maxandersen but even with `--fresh` it does not solve:

```
jbang-catalog $ jbang --fresh --verbose edit --open=code xls2dmn.java
[jbang] jbang version 0.78.0
[jbang] Resolving dependencies...
[jbang]     Resolving org.kie:kie-dmn-xls2dmn-cli:RELEASE...[jbang] [ERROR] Could not resolve dependency org.kie:kie-dmn-xls2dmn-cli:RELEASE
dev.jbang.cli.ExitException: Could not resolve dependency org.kie:kie-dmn-xls2dmn-cli:RELEASE
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:201)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at dev.jbang.dependencies.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:208)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:113)
	at dev.jbang.dependencies.DependencyUtil.resolveDependencies(DependencyUtil.java:62)
	at dev.jbang.source.ScriptSource.resolveClassPath(ScriptSource.java:210)
	at dev.jbang.source.RunContext.resolveClassPath(RunContext.java:261)
	at dev.jbang.cli.Edit.createProjectForEdit(Edit.java:215)
	at dev.jbang.cli.Edit.doCall(Edit.java:70)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:85)
	at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:135)
	at dev.jbang.cli.Jbang$3.handle(Jbang.java:130)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE, caused by: Failed to resolve version for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
	at dev.jbang.dependencies.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:194)
	... 25 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:353)
	at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
	at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
	... 29 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:309)
	... 31 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:218)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:171)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:541)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:524)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:412)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:365)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.process(DefaultDependencyCollector.java:352)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 32 more
Caused by: org.eclipse.aether.resolution.VersionResolutionException: Failed to resolve version for org.kie:kie-dmn-xls2dmn-cli:jar:RELEASE
	at org.apache.maven.repository.internal.DefaultVersionResolver.resolveVersion(DefaultVersionResolver.java:276)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:204)
	... 39 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues
```

is there a way I can brutally erase any jbang cache? I'm on Max OSX

**Comment by tarilabs** [comment]
Hi @quintesse regarding your https://github.com/jbangdev/jbang/issues/985#issuecomment-908176599 , I believe that is a bit source of confusion.
AFAIK, the deprecation affect Maven **plugin** versions you use in the pom:

> Plugin Metaversion Resolution
Internally, Maven 2.x used the special version markers RELEASE and LATEST to support automatic plugin version resolution. These metaversions were also recognized in the <version> element for a <plugin> declaration. For the sake of reproducible builds, Maven 3.x no longer supports usage of these metaversions in the POM. As a result, users will need to replace occurrences of these metaversions with a concrete version.

[source](https://cwiki.apache.org/confluence/display/MAVEN/Maven+3.x+Compatibility+Notes#Maven3.xCompatibilityNotes-PluginMetaversionResolution)

So that said it does not say anything about deprecation in general of these metaversions, while of course it encourages for CI purposes not to use them (which is _not_ implying deprecation for normal dependency versions)

If you have a reference which actually describe deprecation also for dependencies, please let me know

**Comment by quintesse** [comment]
> is there a way I can brutally erase any jbang cache? I'm on Max OSX

Yes, you can always simply do `rm -rf ~/.jbang/cache` 

> So that said it does not say anything about deprecation in general of these metaversions

Indeed, it seems to reefer to plugins only. People seem to strongly advise against using it though and never even having seen it used myself I just assumed it referred to versions in general :-)

**Comment by quintesse** [comment]
Btw, could you perhaps instead of deleting rename the cache folder? See if that fixes things and then rename it back to see if the problem returns?
Because in that case we might be interested in receiving a copy of your cache folder to analyze what the problem is!

**Comment by tarilabs** [comment]
I've tried deleting locally 

```
~/.jbang/cache
~/.m2/org/kie
```

but this problem persists, at least locally for me... this is very weird.

**Comment by tarilabs** [comment]
wait nevermind, I didn't actually delete the local m2 repo... lemme try that.

**Comment by tarilabs** [comment]
BINGO ! It was something bizarre in the local .m2 🤷

**Comment by tarilabs** [comment]
After deleting `~/.m2/repository/org/kie` locally, this worked.

**Comment by quintesse** [comment]
Ok, good to hear you found the solution! 👍
